// src/modules/audiences/audience-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { Audience, AudienceStatus, AudienceType1 } from './entities/audience.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les audiences.
 * Logique métier :
 *   - dossier + jurisdiction + date + heure obligatoires
 *   - Format heure HH:MM
 *   - Status par défaut : SCHEDULED
 *   - Transitions automatiques :
 *     · status=HELD sans decision_date → today
 *     · status=POSTPONED → vérifier postponed_to
 */
@Injectable()
export class AudienceWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(Audience)
    private readonly audienceRepo: Repository<Audience>,
  ) {
    super('audiences', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      dossier_id: { description: 'ID du dossier. Peut fournir "dossier" avec son numéro.', required: true },
      jurisdiction_id: { description: 'ID du tribunal. Peut fournir "jurisdiction" avec le nom.', required: true },
      audience_date: { description: 'Date (YYYY-MM-DD)', example: '2026-06-15', required: true },
      audience_time: { description: 'Heure (HH:MM)', example: '14:30', required: true },
      type: { description: '0=Plaidoirie, 1=Délibération, 2=Jugement, 3=Conciliation', example: '0' },
      status: { description: '0=Programmée, 1=Tenue, 2=Reportée, 3=Annulée', example: '0' },
      judge_name: { description: 'Nom du juge', example: 'Madame la Présidente Dupont' },
      room: { description: 'Salle d\'audience', example: 'Salle 14' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.dossier_id) errors.push('Le dossier est requis (dossier_id ou dossier)');
      if (!fields.jurisdiction_id) errors.push('La juridiction est requise (jurisdiction_id ou jurisdiction)');
      if (!fields.audience_date) errors.push('La date d\'audience est requise (audience_date)');
      if (!fields.audience_time) errors.push('L\'heure d\'audience est requise (audience_time, format HH:MM)');
    }
    if (fields.audience_time && !/^\d{1,2}:\d{2}$/.test(String(fields.audience_time))) {
      errors.push('Le format de l\'heure doit être HH:MM (ex: 14:30)');
    }
    if (fields.status === AudienceStatus.POSTPONED && !fields.postponed_to) {
      // On laisse passer mais on log
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    const data = {
      ...safeFields,
      audience_date: new Date(safeFields.audience_date),
      type: safeFields.type !== undefined ? Number(safeFields.type) : AudienceType1.HEARING,
      status: safeFields.status !== undefined ? Number(safeFields.status) : AudienceStatus.SCHEDULED,
      reminder_sent: safeFields.reminder_sent ?? false,
    };

    const record = this.audienceRepo.create(data);
    const saved = await this.audienceRepo.save(record) as unknown as Audience;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Audience programmée le ${new Date(saved.audience_date).toLocaleDateString('fr-FR')} à ${saved.audience_time}`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const audience = await this.audienceRepo.findOne({ where: { id: entityId as any } });
    if (!audience) throw new NotFoundException(`Audience ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(audience, safeFields);

    // Transitions auto
    if (safeFields.status === AudienceStatus.HELD && !audience.decision_date) {
      audience.decision_date = new Date();
    }

    const saved = await this.audienceRepo.save(audience);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Audience ${entityId} mise à jour`,
    };
  }
}
