// src/modules/paiement/paiement-write.handler.ts
import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { Paiement } from './entities/paiement.entity';
import { ModePaiement, StatutPaiement } from './dto/create-paiement.dto';
import { Facture } from '../facture/entities/facture.entity';
import { StatutFacture } from '../facture/dto/create-facture.dto';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les paiements clients.
 * Logique métier :
 *   - Facture obligatoire (FK validée)
 *   - Montant > 0
 *   - Status par défaut : VALIDE (paiement enregistré = encaissé)
 *   - Après INSERT/UPDATE : recalcule le status de la facture parente
 *     (ENVOYEE / PARTIELLEMENT_PAYEE / PAYEE)
 */
@Injectable()
export class PaiementWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(Paiement)
    private readonly paiementRepo: Repository<Paiement>,
    @InjectRepository(Facture)
    private readonly factureRepo: Repository<Facture>,
    private readonly eventEmitter: EventEmitter2,
  ) {
    super('paiements', dataSource, schemaMetadata, entityResolver);
  }

  // ── Schema enrichi ─────────────────────────────────────────────────────────

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      factureId: {
        description: 'ID (UUID) de la facture associée. Peut aussi fournir "facture" avec son numéro.',
        example: 'FAC-2026-0001-AB12',
        required: true,
      },
      montant: {
        description: 'Montant payé (> 0). Doit être ≤ reste à payer de la facture.',
        example: '1500.00',
        required: true,
      },
      modePaiement: {
        description: '0=VIREMENT, 1=CHEQUE, 2=ESPECES, 3=CARTE, 4=PRELEVEMENT, 5=Mobile, 6=AUTRE',
        example: '0',
      },
      status: {
        description: '0=EN_ATTENTE, 1=VALIDE, 2=REJETE, 3=ANNULE',
        example: '1',
      },
      datePaiement: {
        description: 'Date du paiement (par défaut: aujourd\'hui)',
        example: '2026-05-15',
      },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  // ── Validation métier ──────────────────────────────────────────────────────

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];

    if (operation === 'INSERT') {
      if (!fields.factureId && !fields.facture_id) {
        errors.push('La facture est requise (factureId ou facture)');
      }
      if (fields.montant === undefined || fields.montant === null) {
        errors.push('Le montant est requis');
      } else if (Number(fields.montant) <= 0) {
        errors.push('Le montant doit être strictement positif');
      }
    } else if (operation === 'UPDATE') {
      if (fields.montant !== undefined && Number(fields.montant) <= 0) {
        errors.push('Le montant doit être strictement positif');
      }
    }

    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  // ── INSERT : validation facture + création + maj status facture ───────────

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // Normaliser FK
    const factureId = safeFields.factureId ?? safeFields.facture_id;
    if (!factureId) throw new BadRequestException('factureId manquant après résolution');

    const facture = await this.factureRepo.findOne({
      where: { id: factureId as string },
      relations: ['paiements'],
    });
    if (!facture) throw new NotFoundException(`Facture ${factureId} introuvable`);

    const montant = Number(safeFields.montant);

    // Refuser dépassement du reste à payer
    const dejaPaye = (facture.paiements ?? [])
      .filter(p => p.status === StatutPaiement.VALIDE)
      .reduce((s, p) => s + Number(p.montant), 0);
    const resteAPayer = Number(facture.montantTTC) - dejaPaye;

    if (montant > resteAPayer + 0.01) {
      throw new BadRequestException(
        `Le montant ${montant.toFixed(2)} € dépasse le reste à payer (${resteAPayer.toFixed(2)} €)`,
      );
    }

    const data = {
      ...safeFields,
      factureId,
      montant,
      datePaiement: safeFields.datePaiement ? new Date(safeFields.datePaiement) : new Date(),
      dateValeur: safeFields.dateValeur ? new Date(safeFields.dateValeur) : new Date(),
      modePaiement:
        safeFields.modePaiement !== undefined
          ? Number(safeFields.modePaiement)
          : ModePaiement.ESPECES,
      status:
        safeFields.status !== undefined ? Number(safeFields.status) : StatutPaiement.VALIDE,
    } as any;

    const paiement = Object.assign(new Paiement(), data);
    const saved = await this.paiementRepo.save(paiement);

    // Mise à jour du status de la facture parente
    const updatedFacture = await this.updateFactureStatus(factureId);
    if (saved.status === StatutPaiement.VALIDE) {
      this.eventEmitter.emit('paiement.valide', { ...saved, facture: updatedFacture ?? facture });
    }

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Paiement de ${montant.toFixed(2)} € enregistré sur la facture ${facture.numero}`,
    };
  }

  // ── UPDATE : maj paiement + recalcul status facture ───────────────────────

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const paiement = await this.paiementRepo.findOne({ where: { id: entityId as any } });
    if (!paiement) throw new NotFoundException(`Paiement ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    const previousStatus = paiement.status;
    Object.assign(paiement, safeFields);
    const saved = await this.paiementRepo.save(paiement);

    const updatedFacture = await this.updateFactureStatus(paiement.factureId);
    if (previousStatus !== StatutPaiement.VALIDE && saved.status === StatutPaiement.VALIDE) {
      this.eventEmitter.emit('paiement.valide', { ...saved, facture: updatedFacture });
    }

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Paiement ${entityId} mis à jour`,
    };
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  /** Recalcule le status de la facture parente en fonction des paiements VALIDES */
  private async updateFactureStatus(factureId: string): Promise<Facture | null> {
    const facture = await this.factureRepo.findOne({
      where: { id: factureId },
      relations: ['paiements', 'client'],
    });
    if (!facture) return null;

    const totalPaye = (facture.paiements ?? [])
      .filter(p => p.status === StatutPaiement.VALIDE)
      .reduce((s, p) => s + Number(p.montant), 0);

    const ttc = Number(facture.montantTTC);
    let newStatus = facture.status;
    if (totalPaye === 0) {
      newStatus = StatutFacture.ENVOYEE;
    } else if (totalPaye < ttc) {
      newStatus = StatutFacture.PARTIELLEMENT_PAYEE;
    } else if (totalPaye >= ttc) {
      newStatus = StatutFacture.PAYEE;
    }

    const previousStatus = facture.status;
    if (newStatus !== facture.status) {
      facture.status = newStatus;
      await this.factureRepo.save(facture);
      this.emitFactureBillableEventIfNeeded(facture, previousStatus);
      this.logger.log(`📊 Status facture ${facture.numero} → ${StatutFacture[newStatus]}`);
    }

    return facture;
  }

  private isBillableFactureStatus(status: StatutFacture): boolean {
    return [
      StatutFacture.ENVOYEE,
      StatutFacture.PARTIELLEMENT_PAYEE,
      StatutFacture.PAYEE,
      StatutFacture.IMPAYEE,
    ].includes(status);
  }

  private emitFactureBillableEventIfNeeded(facture: Facture, previousStatus: StatutFacture): void {
    if (previousStatus === facture.status) return;
    if (!this.isBillableFactureStatus(facture.status)) return;

    this.eventEmitter.emit('facture.envoyee', facture);
  }
}
