// src/modules/procedure/write/procedure-instance-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { ProcedureInstance } from '../entities/procedure-instance.entity';
import { ProcedureTemplate } from '../entities/procedure-template.entity';
import { Stage } from '../entities/stage.entity';
import { InstanceStatus } from '../entities/enums/instance-status.enum';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les instances de procédure.
 * Logique métier :
 *   - template + title obligatoires
 *   - currentStageId par défaut = première étape du template (order=0/1)
 *   - Status par défaut : ACTIVE
 */
@Injectable()
export class ProcedureInstanceWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(ProcedureInstance)
    private readonly instanceRepo: Repository<ProcedureInstance>,
    @InjectRepository(ProcedureTemplate)
    private readonly templateRepo: Repository<ProcedureTemplate>,
    @InjectRepository(Stage)
    private readonly stageRepo: Repository<Stage>,
  ) {
    super('procedure_instances', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      templateId: { description: 'ID du modèle de procédure (UUID). Peut fournir "template" avec le nom.', required: true },
      title: { description: 'Titre de l\'instance', example: 'Procédure contentieuse - Dossier Dupont', required: true },
      currentStageId: { description: 'ID de l\'étape courante (auto-rempli si absent → 1ère étape du template)' },
      status: { description: "BD: 'active', 'suspended', 'closed', 'abandoned', 'completed', 'paused', 'in_progress'.", example: 'active' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.templateId) errors.push('Le modèle de procédure est requis (templateId ou template)');
      if (!fields.title) errors.push('Le titre est requis');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // Si currentStageId absent → prendre la première étape du template
    // (les étapes système — ex: "Ouverture" runtime — sont exclues)
    if (!safeFields.currentStageId && safeFields.templateId) {
      const firstStage = await this.stageRepo
        .createQueryBuilder('s')
        .where('s.templateId = :tid', { tid: safeFields.templateId })
        .andWhere('s.isSystem = :sys', { sys: false })
        .orderBy('s.order', 'ASC')
        .getOne();
      if (firstStage) {
        safeFields.currentStageId = firstStage.id;
        this.logger.log(`📌 Première étape auto-assignée: "${firstStage.name}"`);
      }
    }

    const data = {
      ...safeFields,
      status: safeFields.status ?? InstanceStatus.ACTIVE,
    };

    const record = this.instanceRepo.create(data);
    const saved = await this.instanceRepo.save(record) as unknown as ProcedureInstance;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Instance de procédure "${saved.title}" créée`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const instance = await this.instanceRepo.findOne({ where: { id: entityId as any } });
    if (!instance) throw new NotFoundException(`Instance ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(instance, safeFields);

    const saved = await this.instanceRepo.save(instance);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Instance "${saved.title}" mise à jour`,
    };
  }
}
