// src/modules/procedure/write/procedure-template-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { ProcedureTemplate } from '../entities/procedure-template.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les modèles de procédure.
 * Logique métier :
 *   - name unique requis
 *   - Dédup par name : on retourne l'existant si déjà présent
 *   - version par défaut = 1
 *   - isActive par défaut = true
 */
@Injectable()
export class ProcedureTemplateWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(ProcedureTemplate)
    private readonly templateRepo: Repository<ProcedureTemplate>,
  ) {
    super('procedure_templates', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      name: { description: 'Nom unique du modèle', example: 'Contentieux civil standard', required: true },
      description: { description: 'Description détaillée du modèle' },
      version: { description: 'Version (défaut: 1)', example: '1' },
      isActive: { description: 'Modèle actif (défaut: true)', example: 'true' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT' && !fields.name) {
      errors.push('Le nom du modèle est requis');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // Dédup par name (contrainte unique)
    if (safeFields.name) {
      const existing = await this.templateRepo.findOne({ where: { name: safeFields.name } });
      if (existing) {
        this.logger.warn(`♻️  Modèle "${existing.name}" déjà existant (ID ${existing.id})`);
        return {
          success: true,
          operation: 'INSERT',
          entityId: existing.id,
          affected: 0,
          data: existing,
          message: `Modèle "${existing.name}" déjà existant (ID: ${existing.id})`,
        };
      }
    }

    const data = {
      ...safeFields,
      version: safeFields.version ?? 1,
      isActive: safeFields.isActive ?? true,
    };

    const record = this.templateRepo.create(data);
    const saved = this.currentQueryRunner
      ? await this.currentQueryRunner.manager.save(record) as unknown as ProcedureTemplate
      : await this.templateRepo.save(record) as unknown as ProcedureTemplate;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Modèle de procédure "${saved.name}" créé`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const template = await this.templateRepo.findOne({ where: { id: entityId as any } });
    if (!template) throw new NotFoundException(`Modèle ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(template, safeFields);

    const saved = await this.templateRepo.save(template);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Modèle "${saved.name}" mis à jour`,
    };
  }
}
