// src/modules/procedure/write/stage-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { Stage } from '../entities/stage.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les étapes d'un modèle.
 * Logique métier :
 *   - templateId + name + order obligatoires
 *   - Si order absent → MAX(order)+1 dans le template
 *   - Dédup par (templateId, name)
 */
@Injectable()
export class StageWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(Stage)
    private readonly stageRepo: Repository<Stage>,
  ) {
    super('stages', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      templateId: { description: 'ID du modèle parent (UUID). Peut fournir "template".', required: true },
      name: { description: 'Nom de l\'étape', example: 'Mise en état', required: true },
      order: { description: 'Position dans le workflow (auto = max+1 si absent)', example: '1' },
      description: { description: 'Description détaillée' },
      canBeSkipped: { description: 'Peut être ignorée (défaut: false)' },
      canBeReentered: { description: 'Réentrable (défaut: true)' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.templateId) errors.push('Le modèle est requis (templateId ou template)');
      if (!fields.name) errors.push('Le nom de l\'étape est requis');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // Dédup par (templateId, name)
    if (safeFields.templateId && safeFields.name) {
      const existing = await this.stageRepo.findOne({
        where: { templateId: safeFields.templateId, name: safeFields.name },
      });
      if (existing) {
        this.logger.warn(`♻️  Étape "${existing.name}" déjà existante dans ce template (ID ${existing.id})`);
        return {
          success: true,
          operation: 'INSERT',
          entityId: existing.id,
          affected: 0,
          data: existing,
          message: `Étape "${existing.name}" déjà existante (ID: ${existing.id})`,
        };
      }
    }

    // Auto-order : MAX(order) + 1
    let order = safeFields.order;
    if (order === undefined || order === null) {
      const max = await this.stageRepo
        .createQueryBuilder('s')
        .select('MAX(s.order)', 'max')
        .where('s.templateId = :tid', { tid: safeFields.templateId })
        .getRawOne();
      order = (max?.max ?? 0) + 1;
    }

    const data = {
      ...safeFields,
      order: Number(order),
      canBeSkipped: safeFields.canBeSkipped ?? false,
      canBeReentered: safeFields.canBeReentered ?? true,
    };

    const record = this.stageRepo.create(data);
    const saved = await this.stageRepo.save(record) as unknown as Stage;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Étape "${saved.name}" (ordre: ${saved.order}) créée`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const stage = await this.stageRepo.findOne({ where: { id: entityId as any } });
    if (!stage) throw new NotFoundException(`Étape ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(stage, safeFields);

    const saved = await this.stageRepo.save(stage);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Étape "${saved.name}" mise à jour`,
    };
  }
}
