// src/modules/procedure/write/sub-stage-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { SubStage } from '../entities/sub-stage.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les sous-étapes.
 * Logique métier :
 *   - stageId + name + order obligatoires
 *   - Si order absent → MAX(order)+1 dans le stage
 *   - Dédup par (stageId, name)
 *   - isMandatory par défaut = true
 */
@Injectable()
export class SubStageWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(SubStage)
    private readonly subStageRepo: Repository<SubStage>,
  ) {
    super('sub_stages', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      stageId: { description: 'ID de l\'étape parente (UUID). Peut fournir "stage".', required: true },
      name: { description: 'Nom de la sous-étape', example: 'Constitution du dossier', required: true },
      order: { description: 'Position dans l\'étape (auto = max+1 si absent)', example: '1' },
      description: { description: 'Description détaillée' },
      isMandatory: { description: 'Obligatoire (défaut: true)', example: 'true' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.stageId) errors.push('L\'étape parente est requise (stageId ou stage)');
      if (!fields.name) errors.push('Le nom de la sous-étape est requis');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // Dédup par (stageId, name)
    if (safeFields.stageId && safeFields.name) {
      const existing = await this.subStageRepo.findOne({
        where: { stageId: safeFields.stageId, name: safeFields.name },
      });
      if (existing) {
        this.logger.warn(`♻️  Sous-étape "${existing.name}" déjà existante (ID ${existing.id})`);
        return {
          success: true,
          operation: 'INSERT',
          entityId: existing.id,
          affected: 0,
          data: existing,
          message: `Sous-étape "${existing.name}" déjà existante (ID: ${existing.id})`,
        };
      }
    }

    // Auto-order
    let order = safeFields.order;
    if (order === undefined || order === null) {
      const max = await this.subStageRepo
        .createQueryBuilder('ss')
        .select('MAX(ss.order)', 'max')
        .where('ss.stageId = :sid', { sid: safeFields.stageId })
        .getRawOne();
      order = (max?.max ?? 0) + 1;
    }

    const data = {
      ...safeFields,
      order: Number(order),
      isMandatory: safeFields.isMandatory ?? true,
    };

    const record = this.subStageRepo.create(data);
    const saved = await this.subStageRepo.save(record) as unknown as SubStage;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Sous-étape "${saved.name}" (ordre: ${saved.order}) créée`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const subStage = await this.subStageRepo.findOne({ where: { id: entityId as any } });
    if (!subStage) throw new NotFoundException(`Sous-étape ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(subStage, safeFields);

    const saved = await this.subStageRepo.save(subStage);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Sous-étape "${saved.name}" mise à jour`,
    };
  }
}
