// src/modules/procedure/write/task-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { Task } from '../entities/task.entity';
import { TaskStatus } from '../entities/enums/instance-status.enum';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les tâches.
 * Logique métier :
 *   - instance + title obligatoires
 *   - Status par défaut : PENDING
 *   - Status COMPLETED → completedAt = today
 *   - dueDate dans le futur (sauf overdue)
 */
@Injectable()
export class TaskWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(Task)
    private readonly taskRepo: Repository<Task>,
  ) {
    super('tasks', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      instanceId: { description: 'ID de l\'instance de procédure (UUID)', required: true },
      title: { description: 'Titre de la tâche', example: 'Signer la convention', required: true },
      description: { description: 'Description détaillée' },
      dueDate: { description: 'Date d\'échéance (YYYY-MM-DD)', example: '2026-06-30' },
      assignedTo: { description: 'ID de l\'utilisateur assigné' },
      status: { description: "BD: 'pending', 'in_progress', 'completed', 'overdue'.", example: 'pending' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.instanceId) errors.push('L\'instance de procédure est requise (instanceId)');
      if (!fields.title) errors.push('Le titre de la tâche est requis');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    const data = {
      ...safeFields,
      dueDate: safeFields.dueDate ? new Date(safeFields.dueDate) : undefined,
      status: safeFields.status ?? TaskStatus.PENDING,
      completedAt:
        safeFields.status === TaskStatus.COMPLETED && !safeFields.completedAt
          ? new Date()
          : safeFields.completedAt,
    };

    const record = this.taskRepo.create(data);
    const saved = await this.taskRepo.save(record) as unknown as Task;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Tâche "${saved.title}" créée`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const task = await this.taskRepo.findOne({ where: { id: entityId as any } });
    if (!task) throw new NotFoundException(`Tâche ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(task, safeFields);

    // Auto-complétion de completedAt si passage à COMPLETED
    if (safeFields.status === TaskStatus.COMPLETED && !task.completedAt) {
      task.completedAt = new Date();
    }

    const saved = await this.taskRepo.save(task);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Tâche "${saved.title}" mise à jour`,
    };
  }
}
