// src/modules/procedure/write/transition-write.handler.ts
import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { Transition, TransitionType } from '../entities/transition.entity';
import { Stage } from '../entities/stage.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les transitions entre étapes.
 * Logique métier :
 *   - fromStageId + toStageId obligatoires et distincts
 *   - templateId déduit des stages si non fourni
 *   - Dédup par (fromStageId, toStageId)
 *   - Type par défaut : MANUAL
 *   - Vérifie que les deux étapes appartiennent au même template
 */
@Injectable()
export class TransitionWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(Transition)
    private readonly transitionRepo: Repository<Transition>,
    @InjectRepository(Stage)
    private readonly stageRepo: Repository<Stage>,
  ) {
    super('transitions', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      fromStageId: { description: 'ID de l\'étape source (UUID). Peut fournir "fromStage".', required: true },
      toStageId: { description: 'ID de l\'étape destination (UUID). Peut fournir "toStage".', required: true },
      type: { description: 'manual (défaut) ou automatic', example: 'manual' },
      label: { description: 'Libellé affiché', example: 'Passer à l\'instruction' },
      isDefault: { description: 'Transition par défaut (défaut: false)' },
      requiresDecision: { description: 'Nécessite une décision explicite (défaut: true)' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.fromStageId) errors.push('L\'étape source est requise (fromStageId)');
      if (!fields.toStageId) errors.push('L\'étape destination est requise (toStageId)');
    }
    if (fields.fromStageId && fields.toStageId && fields.fromStageId === fields.toStageId) {
      errors.push('L\'étape source et destination doivent être différentes (' + fields.fromStageId + ' === ' + fields.toStageId + ')');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // Dédup par (fromStageId, toStageId)
    const existing = await this.transitionRepo.findOne({
      where: { fromStageId: safeFields.fromStageId, toStageId: safeFields.toStageId },
    });
    if (existing) {
      this.logger.warn(`♻️  Transition déjà existante (ID ${existing.id})`);
      return {
        success: true,
        operation: 'INSERT',
        entityId: existing.id,
        affected: 0,
        data: existing,
        message: `Transition déjà existante (ID: ${existing.id})`,
      };
    }

    // Cohérence : les deux stages doivent appartenir au même template
    const [fromStage, toStage] = await Promise.all([
      this.stageRepo.findOne({ where: { id: safeFields.fromStageId } }),
      this.stageRepo.findOne({ where: { id: safeFields.toStageId } }),
    ]);
    if (!fromStage) throw new NotFoundException(`Étape source ${safeFields.fromStageId} introuvable`);
    if (!toStage) throw new NotFoundException(`Étape destination ${safeFields.toStageId} introuvable`);

    // Si les templateId diffèrent, on tente une récupération :
    // l'EntityResolver a peut-être trouvé une étape orpheline d'un échec précédent
    // (les handlers bypassaient la transaction avec repo.save() avant le fix).
    // On cherche les étapes par nom avec le templateId de la transition (auto-injecté
    // depuis le plan context, donc correct).
    if (fromStage.templateId !== toStage.templateId) {
      const transitionTemplateId = safeFields.templateId;

      if (transitionTemplateId) {
        this.logger.warn(
          `⚠️  templateId différent entre fromStage (${fromStage.templateId}) et toStage (${toStage.templateId}) — ` +
          `tentative de récupération avec templateId=${transitionTemplateId} depuis le plan`,
        );

        const [correctFrom, correctTo] = await Promise.all([
          this.stageRepo.findOne({
            where: { templateId: transitionTemplateId, name: fromStage.name },
          }),
          this.stageRepo.findOne({
            where: { templateId: transitionTemplateId, name: toStage.name },
          }),
        ]);

        if (correctFrom && correctTo && correctFrom.id !== correctTo.id) {
          this.logger.log(
            `✅ Récupération réussie : fromStage → "${correctFrom.name}" (${correctFrom.id}), ` +
            `toStage → "${correctTo.name}" (${correctTo.id})`,
          );
          safeFields.fromStageId = correctFrom.id;
          safeFields.toStageId = correctTo.id;
        } else {
          this.logger.warn(
            `⚠️  Récupération impossible — étapes introuvables avec templateId=${transitionTemplateId}` +
            ` (from="${fromStage.name}", to="${toStage.name}")`,
          );
        }
      } else {
        this.logger.warn(
          `⚠️  Aucun templateId sur la transition — impossible de récupérer, ` +
          `fromStage.templateId=${fromStage.templateId}, toStage.templateId=${toStage.templateId}`,
        );
      }

      // Vérification finale après tentative de récupération
      if (safeFields.fromStageId === safeFields.toStageId) {
        throw new BadRequestException(
          `L'étape source et destination doivent être différentes (${safeFields.fromStageId} === ${safeFields.toStageId})`,
        );
      }
    }

    const data = {
      ...safeFields,
      templateId: safeFields.templateId ?? fromStage.templateId,
      type: safeFields.type ?? TransitionType.MANUAL,
      isDefault: safeFields.isDefault ?? false,
      requiresDecision: safeFields.requiresDecision ?? true,
      requiresValidation: safeFields.requiresValidation ?? false,
    };

    const record = this.transitionRepo.create(data);
    const saved = await this.transitionRepo.save(record) as unknown as Transition;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Transition "${fromStage.name}" → "${toStage.name}" créée`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const transition = await this.transitionRepo.findOne({ where: { id: entityId as any } });
    if (!transition) throw new NotFoundException(`Transition ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(transition, safeFields);

    const saved = await this.transitionRepo.save(transition);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Transition ${entityId} mise à jour`,
    };
  }
}
