import { DataSource } from 'typeorm';
import { Seeder } from 'typeorm-extension';

import { DocumentCategory } from '../entities/document-category.entity';

export default class DocumentCategorySeeder implements Seeder {
  public async run(
    dataSource: DataSource
  ): Promise<any> {
    const repository = dataSource.getRepository(DocumentCategory);

    const categories = [
      // ==================== CONTRACTUEL & JURIDIQUE ====================
      {
        code: 'CONTRACT_BASIC',
        name: 'Contrats standards',
        description: 'Contrats de vente, location, prestation de services standards',
        icon: 'file-contract',
        color: '#2563EB',
        sort_order: 1,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 3650, // 10 ans
          legal_retention_period_2026: '5 à 10 ans (prescription commerciale)',
          confidentiality_level: 'confidential',
          legal_importance: 'high',
          requires_signature: true,
          template_available: true,
          version_control: true,
          applicable_laws: ['Code de Commerce', 'Code des Obligations'],
        },
      },
      {
        code: 'CONTRACT_COMPLEX',
        name: 'Contrats complexes',
        description: 'Contrats d\'affaires, joint-ventures, accords de partenariat',
        icon: 'file-signature',
        color: '#1D4ED8',
        sort_order: 2,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300, // 20 ans
          legal_retention_period_2026: '10 à 30 ans (selon objet)',
          confidentiality_level: 'strictly_confidential',
          legal_importance: 'critical',
          requires_legal_review: true,
          requires_signature: true,
          version_control: true,
          board_approval: true,
        },
      },
      {
        code: 'CONTRACT_AMENDMENT',
        name: 'Avenants et modifications',
        description: 'Avenants aux contrats, modifications, résiliations',
        icon: 'file-edit',
        color: '#3B82F6',
        sort_order: 3,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 3650,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'confidential',
          related_to: 'CONTRACT_BASIC,CONTRACT_COMPLEX',
          version_control: true,
          requires_original_reference: true,
        },
      },
      {
        code: 'CONTRACT_INTERNATIONAL',
        name: 'Contrats internationaux',
        description: 'Contrats avec des parties étrangères, accords transfrontaliers',
        icon: 'globe',
        color: '#1E40AF',
        sort_order: 4,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 10950, // 30 ans
          legal_retention_period_2026: '10 à 30 ans',
          confidentiality_level: 'strictly_confidential',
          legal_importance: 'critical',
          international_laws: true,
          conflict_of_laws: true,
          translation_required: true,
        },
      },

      // ==================== PROCÉDURE & CONTENTIEUX ====================
      {
        code: 'LITIGATION_INITIATION',
        name: 'Initiation de procédure',
        description: 'Assignations, citations, requêtes introductives',
        icon: 'gavel',
        color: '#DC2626',
        sort_order: 5,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '10 à 30 ans (dossier judiciaire)',
          confidentiality_level: 'confidential',
          legal_importance: 'critical',
          court_registration: true,
          filing_deadlines: true,
          proof_of_service: true,
        },
      },
      {
        code: 'LITIGATION_MOTIONS',
        name: 'Mémoires et conclusions',
        description: 'Mémoires en défense, conclusions, notes de plaidoirie',
        icon: 'balance-scale',
        color: '#B91C1C',
        sort_order: 6,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '10 ans minimum',
          confidentiality_level: 'confidential',
          filing_deadlines: true,
          lawyer_privilege: true,
          case_strategy: true,
        },
      },
      {
        code: 'JUDGMENTS',
        name: 'Décisions judiciaires',
        description: 'Jugements, arrêts, ordonnances, décisions arbitrales',
        icon: 'scale-balanced',
        color: '#991B1B',
        sort_order: 7,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 10950,
          legal_retention_period_2026: 'Permanent ou 30 ans+',
          confidentiality_level: 'confidential',
          legal_importance: 'critical',
          enforceability: true,
          appeal_deadlines: true,
          res_judicata: true,
        },
      },
      {
        code: 'LITIGATION_SETTLEMENT',
        name: 'Accords transactionnels',
        description: 'Transactions, conciliations, médiations',
        icon: 'handshake',
        color: '#EF4444',
        sort_order: 8,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'strictly_confidential',
          requires_signature: true,
          finality_clause: true,
          confidentiality_clause: true,
        },
      },
      {
        code: 'APPEALS',
        name: 'Procédures d\'appel',
        description: 'Appels, pourvois, recours',
        icon: 'arrows-rotate',
        color: '#F87171',
        sort_order: 9,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 10950,
          legal_retention_period_2026: '10 à 30 ans',
          confidentiality_level: 'confidential',
          appeal_deadlines: true,
          higher_court: true,
          suspensive_effect: true,
        },
      },

      // ==================== PREUVES & ÉLÉMENTS DE DOSSIER ====================
      {
        code: 'EVIDENCE_DOCUMENTARY',
        name: 'Preuves documentaires',
        description: 'Documents originaux, copies certifiées, pièces justificatives',
        icon: 'file-certificate',
        color: '#059669',
        sort_order: 10,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '5 à 10 ans (selon pièce)',
          confidentiality_level: 'confidential',
          chain_of_custody: true,
          authenticity_verification: true,
          notarization_possible: true,
          original_vs_copy: true,
        },
      },
      {
        code: 'EVIDENCE_DIGITAL',
        name: 'Preuves numériques',
        description: 'Emails, captures d\'écran, logs, métadonnées',
        icon: 'microchip',
        color: '#10B981',
        sort_order: 11,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 à 10 ans (avec horodatage)',
          confidentiality_level: 'confidential',
          digital_forensics: true,
          hash_verification: true,
          timestamp_required: true,
          electronic_signature: true,
        },
      },
      {
        code: 'EVIDENCE_EXPERT',
        name: 'Rapports d\'expertise',
        description: 'Rapports d\'experts judiciaires, contre-expertises',
        icon: 'user-tie',
        color: '#047857',
        sort_order: 12,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '10 ans',
          confidentiality_level: 'confidential',
          expert_qualification: true,
          cross_examination: true,
          requires_validation: true,
          methodology_documented: true,
        },
      },
      {
        code: 'EVIDENCE_TESTIMONIAL',
        name: 'Témoignages et dépositions',
        description: 'Déclarations sous serment, procès-verbaux d\'audition',
        icon: 'comment-dots',
        color: '#065F46',
        sort_order: 13,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'confidential',
          witness_identification: true,
          oath_required: true,
          cross_examination: true,
        },
      },

      // ==================== ADMINISTRATIF & RÉGLEMENTAIRE ====================
      {
        code: 'REGULATORY_COMPLIANCE',
        name: 'Conformité réglementaire',
        description: 'Documents de conformité, déclarations, autorisations',
        icon: 'clipboard-check',
        color: '#7C3AED',
        sort_order: 14,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'internal',
          regulatory_body: true,
          renewal_deadlines: true,
          compliance_audit: true,
          gdpr_compliance: true,
        },
      },
      {
        code: 'GOVERNMENT_CORRESPONDENCE',
        name: 'Correspondance officielle',
        description: 'Échanges avec administrations, réponses officielles',
        icon: 'building-columns',
        color: '#8B5CF6',
        sort_order: 15,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 3650,
          legal_retention_period_2026: '5 ans',
          confidentiality_level: 'confidential',
          official_registration: true,
          response_deadlines: true,
          administrative_law: true,
        },
      },
      {
        code: 'LICENSES_PERMITS',
        name: 'Licences et permis',
        description: 'Licences d\'exploitation, permis de construire, agréments',
        icon: 'id-card',
        color: '#A78BFA',
        sort_order: 16,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: 'Jusqu\'à expiration + 5 ans',
          confidentiality_level: 'confidential',
          expiration_dates: true,
          renewal_required: true,
          regulatory_fees: true,
        },
      },

      // ==================== FINANCIER & COMPTABLE ====================
      {
        code: 'FINANCIAL_INVOICES',
        name: 'Factures et reçus',
        description: 'Factures clients, factures fournisseurs, reçus de paiement',
        icon: 'receipt',
        color: '#F59E0B',
        sort_order: 17,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 3650,
          legal_retention_period_2026: '10 ans (comptable/fiscale)',
          confidentiality_level: 'confidential',
          tax_deduction: true,
          accounting_period: true,
          payment_terms: true,
          vat_compliance: true,
        },
      },
      {
        code: 'FINANCIAL_STATEMENTS',
        name: 'États financiers',
        description: 'Bilans, comptes de résultat, annexes',
        icon: 'chart-line',
        color: '#D97706',
        sort_order: 18,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '10 ans après clôture',
          confidentiality_level: 'strictly_confidential',
          audited: true,
          fiscal_year: true,
          certification_required: true,
          shareholder_approval: true,
        },
      },
      {
        code: 'FINANCIAL_AUDIT',
        name: 'Documents d\'audit',
        description: 'Rapports d\'audit, lettres de mission, comptes annuels',
        icon: 'magnifying-glass-chart',
        color: '#B45309',
        sort_order: 19,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '10 ans',
          confidentiality_level: 'strictly_confidential',
          auditor_independence: true,
          management_representation: true,
          audit_trail: true,
        },
      },
      {
        code: 'FINANCIAL_TAX',
        name: 'Documents fiscaux',
        description: 'Déclarations fiscales, avis d\'imposition, justificatifs',
        icon: 'scale-unbalanced',
        color: '#92400E',
        sort_order: 20,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '6 à 10 ans (jusqu\'à 10 en fraude)',
          confidentiality_level: 'strictly_confidential',
          tax_authority: true,
          statute_of_limitations: true,
          penalty_risks: true,
          tax_withholding: true,
        },
      },
      {
        code: 'FINANCIAL_BANKING',
        name: 'Documents bancaires',
        description: 'Relevés bancaires, contrats de prêt, garanties',
        icon: 'building-bank',
        color: '#78350F',
        sort_order: 21,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'strictly_confidential',
          bank_secrecy: true,
          interest_calculation: true,
          loan_guarantees: true,
        },
      },

      // ==================== CORRESPONDANCE & COMMUNICATION ====================
      {
        code: 'CORRESPONDENCE_LEGAL',
        name: 'Correspondance juridique',
        description: 'Lettres d\'avocats, mises en demeure, notifications',
        icon: 'envelope-open-text',
        color: '#0EA5E9',
        sort_order: 22,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 3650,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'confidential',
          legal_privilege: true,
          response_required: true,
          proof_of_receipt: true,
        },
      },
      {
        code: 'CORRESPONDENCE_INTERNAL',
        name: 'Correspondance interne',
        description: 'Mémos internes, notes de service, emails internes',
        icon: 'envelope',
        color: '#38BDF8',
        sort_order: 23,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 1825,
          legal_retention_period_2026: '3 à 5 ans',
          confidentiality_level: 'internal',
          department_circulation: true,
          approval_workflow: true,
          internal_policies: true,
        },
      },
      {
        code: 'COMMUNICATION_CLIENT',
        name: 'Communication client',
        description: 'Échanges avec clients, confirmations, relances',
        icon: 'comments',
        color: '#7DD3FC',
        sort_order: 24,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 3650,
          legal_retention_period_2026: '5 ans',
          confidentiality_level: 'confidential',
          client_confidentiality: true,
          service_level_agreement: true,
          complaint_handling: true,
        },
      },

      // ==================== RESSOURCES HUMAINES ====================
      {
        code: 'HR_CONTRACTS',
        name: 'Contrats de travail',
        description: 'CDI, CDD, contrats d\'intérim, annexes',
        icon: 'file-signature',
        color: '#9333EA',
        sort_order: 25,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '5 ans après fin de contrat (employeur) / À vie (salarié)',
          confidentiality_level: 'strictly_confidential',
          employee_consent: true,
          social_laws: true,
          termination_rules: true,
          employee_rights: true,
        },
      },
      {
        code: 'HR_PERSONNEL_FILES',
        name: 'Dossiers du personnel',
        description: 'CV, diplômes, évaluations, promotions',
        icon: 'folder-user',
        color: '#A855F7',
        sort_order: 26,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '5 ans après départ',
          confidentiality_level: 'strictly_confidential',
          gdpr_compliance: true,
          access_restricted: true,
          retention_specific: true,
          employee_privacy: true,
        },
      },
      {
        code: 'HR_PAYROLL',
        name: 'Documents de paie',
        description: 'Bulletins de paie, déclarations sociales, attestations',
        icon: 'money-bill-wave',
        color: '#C084FC',
        sort_order: 27,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 ans (employeur) / À vie (salarié)',
          confidentiality_level: 'strictly_confidential',
          tax_withholding: true,
          social_security: true,
          employee_access: true,
          pension_rights: true,
        },
      },
      {
        code: 'HR_DISCIPLINARY',
        name: 'Documents disciplinaires',
        description: 'Avertissements, procès-verbaux, décisions',
        icon: 'exclamation-triangle',
        color: '#D946EF',
        sort_order: 28,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 ans',
          confidentiality_level: 'strictly_confidential',
          employee_rights: true,
          appeal_process: true,
          disciplinary_procedure: true,
        },
      },

      // ==================== TECHNIQUE & EXPERTISE ====================
      {
        code: 'TECHNICAL_REPORTS',
        name: 'Rapports techniques',
        description: 'Études techniques, analyses, diagnostics',
        icon: 'file-chart-line',
        color: '#64748B',
        sort_order: 29,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'confidential',
          technical_validation: true,
          methodology_documented: true,
          peer_review: true,
          quality_assurance: true,
        },
      },
      {
        code: 'TECHNICAL_PATENTS',
        name: 'Brevets et propriété intellectuelle',
        description: 'Dépôts de brevet, droits d\'auteur, marques',
        icon: 'copyright',
        color: '#475569',
        sort_order: 30,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 14600, // 40 ans
          legal_retention_period_2026: 'Durée de protection + 5 ans',
          confidentiality_level: 'strictly_confidential',
          intellectual_property: true,
          international_protection: true,
          renewal_fees: true,
          infringement_monitoring: true,
        },
      },
      {
        code: 'TECHNICAL_SPECIFICATIONS',
        name: 'Spécifications techniques',
        description: 'Cahiers des charges, normes, procédures',
        icon: 'list-check',
        color: '#334155',
        sort_order: 31,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'internal',
          version_control: true,
          compliance_certification: true,
          industry_standards: true,
        },
      },
      {
        code: 'TECHNICAL_INSPECTION',
        name: 'Rapports d\'inspection',
        description: 'Contrôles qualité, audits techniques, vérifications',
        icon: 'magnifying-glass',
        color: '#1E293B',
        sort_order: 32,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'confidential',
          inspector_qualification: true,
          corrective_actions: true,
          follow_up_required: true,
        },
      },

      // ==================== GOUVERNANCE & CONFORMITÉ ====================
      {
        code: 'GOVERNANCE_BOARD',
        name: 'Documents de gouvernance',
        description: 'Procès-verbaux d\'AG, décisions du conseil',
        icon: 'users-gear',
        color: '#6366F1',
        sort_order: 33,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 10950,
          legal_retention_period_2026: '10 ans minimum',
          confidentiality_level: 'strictly_confidential',
          board_approval: true,
          shareholder_rights: true,
          corporate_governance: true,
          regulatory_compliance: true,
        },
      },
      {
        code: 'COMPLIANCE_POLICIES',
        name: 'Politiques et procédures',
        description: 'Politiques internes, codes de conduite, chartes',
        icon: 'book',
        color: '#4F46E5',
        sort_order: 34,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 ans (après mise à jour)',
          confidentiality_level: 'internal',
          version_history: true,
          employee_acknowledgment: true,
          regular_review: true,
        },
      },
      {
        code: 'RISK_MANAGEMENT',
        name: 'Gestion des risques',
        description: 'Analyses de risques, plans de continuité, assurances',
        icon: 'triangle-exclamation',
        color: '#3730A3',
        sort_order: 35,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'confidential',
          risk_assessment: true,
          mitigation_strategies: true,
          insurance_coverage: true,
          business_continuity: true,
        },
      },

      // ==================== PROPRIÉTÉ & BIENS ====================
      {
        code: 'REAL_ESTATE',
        name: 'Documents immobiliers',
        description: 'Actes de propriété, baux, diagnostics',
        icon: 'house',
        color: '#F97316',
        sort_order: 36,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 10950,
          legal_retention_period_2026: '30 ans (immobilier) ou permanent',
          confidentiality_level: 'strictly_confidential',
          notarization_required: true,
          land_registry: true,
          property_tax: true,
          title_deed: true,
        },
      },
      {
        code: 'ASSETS_INVENTORY',
        name: 'Inventaires de biens',
        description: 'Listes d\'actifs, fiches d\'inventaire, amortissements',
        icon: 'clipboard-list',
        color: '#EA580C',
        sort_order: 37,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '10 ans',
          confidentiality_level: 'confidential',
          asset_valuation: true,
          depreciation_schedule: true,
          insurance_value: true,
        },
      },

      // ==================== INTERNATIONAL & MULTILINGUE ====================
      {
        code: 'INTERNATIONAL_TRADE',
        name: 'Commerce international',
        description: 'Documents douaniers, incoterms, lettres de crédit',
        icon: 'plane',
        color: '#06B6D4',
        sort_order: 38,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'confidential',
          customs_regulations: true,
          international_laws: true,
          currency_conversion: true,
          incoterms: true,
        },
      },
      {
        code: 'TRANSLATIONS',
        name: 'Traductions certifiées',
        description: 'Documents traduits, certifications de traduction',
        icon: 'language',
        color: '#0891B2',
        sort_order: 39,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'confidential',
          certified_translator: true,
          source_document_link: true,
          legal_equivalence: true,
        },
      },

      // ==================== SANTÉ & SÉCURITÉ ====================
      {
        code: 'HEALTH_SAFETY',
        name: 'Santé et sécurité',
        description: 'Documents SST, registres, plans de prévention',
        icon: 'shield-heart',
        color: '#EC4899',
        sort_order: 40,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: '5 à 10 ans',
          confidentiality_level: 'confidential',
          regulatory_compliance: true,
          incident_reporting: true,
          training_records: true,
          workplace_safety: true,
        },
      },

      // ==================== CONFIDENTIALITÉ & PROTECTION ====================
      {
        code: 'CONFIDENTIALITY_NDA',
        name: 'Accords de confidentialité',
        description: 'NDA, clauses de non-concurrence',
        icon: 'lock',
        color: '#111827',
        sort_order: 41,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 7300,
          legal_retention_period_2026: '5 ans après fin + durée clause',
          confidentiality_level: 'strictly_confidential',
          parties_bound: true,
          duration_specified: true,
          penalty_clauses: true,
          trade_secrets: true,
        },
      },

      // ==================== ARCHIVES & HISTORIQUE ====================
      {
        code: 'ARCHIVE_PERMANENT',
        name: 'Archives permanentes',
        description: 'Documents à conservation permanente',
        icon: 'box-archive',
        color: '#374151',
        sort_order: 42,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 0, // Permanent
          legal_retention_period_2026: 'Permanent',
          confidentiality_level: 'confidential',
          historical_value: true,
          preservation_required: true,
          access_restricted: true,
          digitization_recommended: true,
        },
      },
      {
        code: 'ARCHIVE_TEMPORARY',
        name: 'Archives temporaires',
        description: 'Documents en attente de destruction',
        icon: 'trash-clock',
        color: '#6B7280',
        sort_order: 43,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 1825,
          legal_retention_period_2026: 'Variable',
          confidentiality_level: 'internal',
          destruction_scheduled: true,
          review_before_destruction: true,
          secure_destruction: true,
        },
      },
      {
        code: 'ARCHIVE_DIGITAL',
        name: 'Archives numériques',
        description: 'Documents archivés électroniquement',
        icon: 'database',
        color: '#9CA3AF',
        sort_order: 44,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 5475,
          legal_retention_period_2026: 'Selon nature originale',
          confidentiality_level: 'confidential',
          digital_preservation: true,
          format_migration: true,
          integrity_checks: true,
          backup_policy: true,
        },
      },

      // ==================== DIVERS & AUTRES ====================
      {
        code: 'MISCELLANEOUS',
        name: 'Divers',
        description: 'Documents ne relevant pas des autres catégories',
        icon: 'folder',
        color: '#6B7280',
        sort_order: 99,
        is_system: true,
        is_active: true,
        metadata: {
          retention_period: 1825,
          legal_retention_period_2026: 'Variable',
          confidentiality_level: 'internal',
          review_required: true,
          recategorization_possible: true,
          temporary_holding: true,
        },
      },
    ];

    for (const categoryData of categories) {
      const existing = await repository.findOne({
        where: { code: categoryData.code }
      });

      if (!existing) {
        const category = repository.create(
          categoryData as Partial<DocumentCategory>
        );
        category.created_at = new Date();
        category.updated_at = new Date();
        await repository.save(category);
        console.log(`✅ Catégorie créée: ${category.name} (${category.code})`);
      } else {
        console.log(`⏭️ Catégorie existante: ${existing.name}`);
      }
    }

    console.log(`\n📊 Résumé: ${categories.length} catégories de documents traitées`);
  }
}