// src/modules/procedures/procedure-type-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { ProcedureType } from './entities/procedure.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les types et sous-types de procédure.
 * Table : procedure_types
 *
 * Logique métier :
 *   - name requis pour INSERT
 *   - code unique : fourni par le LLM ou auto-généré depuis le nom
 *   - Dédup par code (contrainte unique) puis par name
 *   - is_subtype=true → parent_id requis, hierarchy_level=2
 *   - is_subtype=false (défaut) → hierarchy_level=1
 *   - is_active=true par défaut
 *   - UPDATE : code immuable après création
 */
@Injectable()
export class ProcedureTypeWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(ProcedureType)
    private readonly typeRepo: Repository<ProcedureType>,
  ) {
    super('procedure_types', dataSource, schemaMetadata, entityResolver);
  }

  // ── Schema override ─────────────────────────────────────────────────────────

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      name: {
        description: 'Nom du type ou sous-type de procédure',
        example: 'Contentieux civil',
        required: true,
      },
      code: {
        description: 'Code unique court (auto-généré depuis le nom si absent)',
        example: 'CONT-CIV',
      },
      description: {
        description: 'Description détaillée du type de procédure',
      },
      is_subtype: {
        description: 'true si c\'est un sous-type, false si type principal (défaut: false)',
        example: 'false',
      },
      parent_id: {
        description: 'ID du type parent — obligatoire si is_subtype=true',
        example: '1',
      },
      is_active: {
        description: 'Actif ou non (défaut: true)',
        example: 'true',
      },
      average_duration: {
        description: 'Durée moyenne de la procédure en jours',
        example: '90',
      },
      procedure_template_id: {
        description: 'ID du modèle de workflow associé (UUID, optionnel)',
      },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  // ── Validation métier ────────────────────────────────────────────────────────

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];

    if (operation === 'INSERT') {
      if (!fields.name) {
        errors.push('Le nom du type de procédure est requis');
      }
      const isSubtype = fields.is_subtype === true || fields.is_subtype === 'true' || fields.is_subtype === 1;
      if (isSubtype && !fields.parent_id) {
        errors.push('Le type parent est requis pour un sous-type (parent_id)');
      }
    }

    if (operation === 'UPDATE') {
      // Empêcher la suppression du nom
      if (fields.name === null || fields.name === '') {
        errors.push('Le nom ne peut pas être supprimé');
      }
    }

    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  // ── INSERT ───────────────────────────────────────────────────────────────────

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    // Sauvegarder le code explicite avant que stripAutoGeneratedFields ne le supprime
    // (car 'code' est dans AUTO_GENERATED_FIELDS du BaseWriteHandler — prudence générique)
    const explicitCode: string | undefined = fields.code ?? fields['code'];

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // ── Résolution du code ────────────────────────────────────────────────────
    let code = explicitCode?.trim() || '';
    if (!code && safeFields.name) {
      code = this.generateCode(safeFields.name);
    }
    code = await this.ensureUniqueCode(code);

    // ── Dédup par code (contrainte unique BDD) ────────────────────────────────
    const existingByCode = await this.typeRepo.findOne({ where: { code } });
    if (existingByCode) {
      this.logger.warn(`♻️  Type "${existingByCode.name}" déjà existant (code: ${code})`);
      return {
        success: true,
        operation: 'INSERT',
        entityId: existingByCode.id,
        affected: 0,
        data: existingByCode,
        message: `Type de procédure "${existingByCode.name}" déjà existant (code: ${code})`,
      };
    }

    // ── Dédup par name ────────────────────────────────────────────────────────
    if (safeFields.name) {
      const existingByName = await this.typeRepo.findOne({ where: { name: safeFields.name } });
      if (existingByName) {
        this.logger.warn(`♻️  Type "${existingByName.name}" déjà existant (ID ${existingByName.id})`);
        return {
          success: true,
          operation: 'INSERT',
          entityId: existingByName.id,
          affected: 0,
          data: existingByName,
          message: `Type de procédure "${existingByName.name}" déjà existant (ID: ${existingByName.id})`,
        };
      }
    }

    // ── Construction des données ──────────────────────────────────────────────
    const isSubtype = safeFields.is_subtype === true
      || safeFields.is_subtype === 'true'
      || safeFields.is_subtype === 1;

    const data = {
      ...safeFields,
      code,
      is_subtype: isSubtype,
      hierarchy_level: safeFields.hierarchy_level ?? (isSubtype ? 2 : 1),
      is_active: safeFields.is_active ?? true,
    };

    const record = this.typeRepo.create(data);
    const saved = await this.typeRepo.save(record) as unknown as ProcedureType;

    this.logger.log(`✅ Type de procédure créé: "${saved.name}" [${saved.code}] (niveau ${saved.hierarchy_level})`);

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Type de procédure "${saved.name}" (${saved.code}) créé${isSubtype ? ' comme sous-type' : ''}`,
    };
  }

  // ── UPDATE ───────────────────────────────────────────────────────────────────

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const type = await this.typeRepo.findOne({ where: { id: entityId as number } });
    if (!type) throw new NotFoundException(`Type de procédure ${entityId} introuvable`);

    const safeFields = this.filterKnownColumns(fields);
    // Le code est immuable après création (clé naturelle + références externes)
    delete safeFields['code'];

    Object.assign(type, safeFields);
    const saved = await this.typeRepo.save(type);

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Type de procédure "${saved.name}" (${saved.code}) mis à jour`,
    };
  }

  // ── Helpers privés ───────────────────────────────────────────────────────────

  /**
   * Génère un code court depuis un nom lisible.
   * Ex: "Contentieux commercial" → "CONT-COMM"
   *     "Droit de la famille"    → "DROIT-FAMI"
   */
  private generateCode(name: string): string {
    const STOP_WORDS = new Set(['de', 'du', 'des', 'la', 'le', 'les', 'et', 'ou', 'en', 'au', 'aux', 'un', 'une']);
    return name
      .normalize('NFD')
      .replace(/[̀-ͯ]/g, '')   // supprimer les accents
      .toUpperCase()
      .replace(/[^A-Z0-9\s]/g, '')       // garder lettres + chiffres + espaces
      .split(/\s+/)
      .filter((w) => w.length > 1 && !STOP_WORDS.has(w.toLowerCase()))
      .slice(0, 3)                       // max 3 mots
      .map((w) => w.slice(0, 4))         // max 4 caractères par mot
      .join('-')
      .slice(0, 50);                     // longueur max colonne
  }

  /**
   * Garantit l'unicité du code en ajoutant un suffixe numérique si nécessaire.
   * Ex: "CONT-CIV" → "CONT-CIV-2" → "CONT-CIV-3" ...
   */
  private async ensureUniqueCode(baseCode: string): Promise<string> {
    let code = baseCode;
    let attempt = 1;
    while (attempt <= 100) {
      const existing = await this.typeRepo.findOne({ where: { code } });
      if (!existing) return code;
      attempt++;
      code = `${baseCode}-${attempt}`;
    }
    // Filet de sécurité extrême
    return `${baseCode.slice(0, 40)}-${Date.now() % 10000}`;
  }
}
