// src/modules/payroll/payroll-period-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { PayrollPeriod, PayrollPeriodStatus } from './entities/payroll-period.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les périodes de paie.
 * Logique métier :
 *   - label, start_date, end_date obligatoires
 *   - end_date > start_date
 *   - Dédup par (label) ET par (start_date+end_date) : une seule période par mois/agence
 *   - Status par défaut : DRAFT
 */
@Injectable()
export class PayrollPeriodWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(PayrollPeriod)
    private readonly periodRepo: Repository<PayrollPeriod>,
  ) {
    super('payroll_period', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      label: { description: 'Libellé de la période', example: 'Paie Mars 2026', required: true },
      start_date: { description: 'Premier jour (YYYY-MM-DD)', example: '2026-03-01', required: true },
      end_date: { description: 'Dernier jour (YYYY-MM-DD)', example: '2026-03-31', required: true },
      status: { description: "BD: 'draft', 'validated', 'paid', 'cancelled'.", example: 'draft' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.label) errors.push('Le libellé est requis (ex: "Paie Mars 2026")');
      if (!fields.start_date) errors.push('La date de début est requise');
      if (!fields.end_date) errors.push('La date de fin est requise');
    }
    if (fields.start_date && fields.end_date) {
      const s = new Date(fields.start_date);
      const e = new Date(fields.end_date);
      if (e <= s) errors.push('La date de fin doit être postérieure à la date de début');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // Dédup par (start_date + end_date + branch_id)
    if (safeFields.start_date && safeFields.end_date) {
      const where: any = {
        start_date: new Date(safeFields.start_date),
        end_date: new Date(safeFields.end_date),
      };
      if (safeFields.branch_id) where.branch_id = safeFields.branch_id;
      const existing = await this.periodRepo.findOne({ where });
      if (existing) {
        this.logger.warn(`♻️  Période de paie existante: "${existing.label}" (ID ${existing.id})`);
        return {
          success: true,
          operation: 'INSERT',
          entityId: existing.id,
          affected: 0,
          data: existing,
          message: `Période "${existing.label}" déjà existante (ID: ${existing.id})`,
        };
      }
    }

    const data = {
      ...safeFields,
      start_date: new Date(safeFields.start_date),
      end_date: new Date(safeFields.end_date),
      status: safeFields.status ?? PayrollPeriodStatus.DRAFT,
    };

    const record = this.periodRepo.create(data);
    const saved = await this.periodRepo.save(record) as unknown as PayrollPeriod;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Période de paie "${saved.label}" créée`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const period = await this.periodRepo.findOne({ where: { id: entityId as any } });
    if (!period) throw new NotFoundException(`Période ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(period, safeFields);
    const saved = await this.periodRepo.save(period);

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Période ${saved.label} mise à jour`,
    };
  }
}
