// src/modules/payroll/payslip-line-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { PayslipLine, PayslipLineType } from './entities/payslip-line.entity';
import { Payslip } from './entities/payslip.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les lignes de fiche de paie.
 * Logique métier :
 *   - payslip + line_type + label + amount obligatoires
 *   - Après INSERT/UPDATE/DELETE : recalcule gross_amount et net_amount de la fiche parente
 *     - gross_amount = somme des lignes BASE_SALARY + BONUS + INTERNAL_COMMISSION + OVERTIME
 *     - net_amount = gross + BENEFIT - DEDUCTION (signes des montants gérés par convention)
 */
@Injectable()
export class PayslipLineWriteHandler extends BaseWriteHandler {
  /** Types qui composent le brut */
  private static readonly GROSS_TYPES = new Set<PayslipLineType>([
    PayslipLineType.BASE_SALARY,
    PayslipLineType.BONUS,
    PayslipLineType.INTERNAL_COMMISSION,
    PayslipLineType.OVERTIME,
  ]);

  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(PayslipLine)
    private readonly lineRepo: Repository<PayslipLine>,
    @InjectRepository(Payslip)
    private readonly payslipRepo: Repository<Payslip>,
  ) {
    super('payslip_line', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      payslip_id: {
        description: 'ID de la fiche de paie parente. Peut fournir "payslip".',
        example: '12',
        required: true,
      },
      line_type: {
        description: 'base_salary, bonus, internal_commission, deduction, benefit, overtime',
        example: 'base_salary',
        required: true,
      },
      label: { description: 'Libellé sur le bulletin', example: 'Salaire de base Mars 2026', required: true },
      amount: {
        description: 'Montant (positif=gain, négatif=retenue par convention)',
        example: '4500.00',
        required: true,
      },
      is_taxable: { description: '1=imposable, 0=non imposable', example: '1' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.payslip_id) errors.push('La fiche de paie est requise (payslip_id ou payslip)');
      if (!fields.line_type) errors.push('Le type de ligne est requis (base_salary, bonus, deduction…)');
      if (!fields.label) errors.push('Le libellé est requis');
      if (fields.amount === undefined || fields.amount === null) errors.push('Le montant est requis');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    const data = {
      ...safeFields,
      amount: Number(safeFields.amount),
      is_taxable: safeFields.is_taxable !== undefined ? Boolean(safeFields.is_taxable) : true,
    };

    const record = this.lineRepo.create(data);
    const saved = await this.lineRepo.save(record) as unknown as PayslipLine;

    // Recalcul des totaux de la fiche parente
    await this.recomputePayslipTotals(saved.payslip_id);

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Ligne "${saved.label}" (${Number(saved.amount).toFixed(2)} €) ajoutée à la fiche ${saved.payslip_id}`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const line = await this.lineRepo.findOne({ where: { id: entityId as any } });
    if (!line) throw new NotFoundException(`Ligne ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(line, safeFields);
    const saved = await this.lineRepo.save(line);

    // Recalcul des totaux
    await this.recomputePayslipTotals(saved.payslip_id);

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Ligne ${entityId} mise à jour, totaux de la fiche recalculés`,
    };
  }

  /** Recalcule gross_amount et net_amount de la fiche depuis ses lignes */
  private async recomputePayslipTotals(payslipId: number): Promise<void> {
    const lines = await this.lineRepo.find({ where: { payslip_id: payslipId } });
    if (lines.length === 0) return;

    let gross = 0;
    let net = 0;
    for (const line of lines) {
      const amount = Number(line.amount);
      if (PayslipLineWriteHandler.GROSS_TYPES.has(line.line_type)) {
        gross += amount;
      }
      net += amount; // somme algébrique : retenues sont négatives par convention
    }

    const payslip = await this.payslipRepo.findOne({ where: { id: payslipId } });
    if (payslip) {
      payslip.gross_amount = Math.round(gross * 100) / 100;
      payslip.net_amount = Math.round(net * 100) / 100;
      await this.payslipRepo.save(payslip);
      this.logger.log(
        `📊 Fiche ${payslipId} recalculée: Brut=${payslip.gross_amount} € / Net=${payslip.net_amount} €`,
      );
    }
  }
}
