// src/modules/payroll/payslip-write.handler.ts
import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { Payslip, PayslipStatus } from './entities/payslip.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les fiches de paie.
 * Logique métier :
 *   - employee + period obligatoires
 *   - gross_amount > 0
 *   - Dédup par (employee_id, period_id) — une seule fiche par couple
 *   - Status par défaut : DRAFT
 *   - Si net_amount non fourni, par défaut = gross_amount
 *   - Si status passe à PAID sans payment_date → today
 */
@Injectable()
export class PayslipWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(Payslip)
    private readonly payslipRepo: Repository<Payslip>,
  ) {
    super('payslip', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      employee_id: {
        description: 'ID du collaborateur. Peut aussi fournir "employee" avec son nom.',
        example: '5',
        required: true,
      },
      period_id: {
        description: 'ID de la période de paie. Peut aussi fournir "period" avec son libellé.',
        example: '3',
        required: true,
      },
      gross_amount: {
        description: 'Salaire brut (> 0)',
        example: '4500.00',
        required: true,
      },
      net_amount: {
        description: 'Net à payer (par défaut = gross_amount)',
        example: '3200.00',
      },
      status: { description: "BD: 'draft', 'validated', 'paid'.", example: 'draft' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.employee_id) errors.push('Le collaborateur est requis (employee_id ou employee)');
      if (!fields.period_id) errors.push('La période de paie est requise (period_id ou period)');
      if (fields.gross_amount === undefined || fields.gross_amount === null) {
        errors.push('Le salaire brut est requis (gross_amount)');
      } else if (Number(fields.gross_amount) <= 0) {
        errors.push('Le salaire brut doit être strictement positif');
      }
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // Dédup : une seule fiche par (employee_id, period_id)
    if (safeFields.employee_id && safeFields.period_id) {
      const existing = await this.payslipRepo.findOne({
        where: {
          employee_id: safeFields.employee_id,
          period_id: safeFields.period_id,
        },
      });
      if (existing) {
        this.logger.warn(
          `♻️  Fiche de paie déjà existante pour employee=${existing.employee_id} period=${existing.period_id} (ID ${existing.id})`,
        );
        return {
          success: true,
          operation: 'INSERT',
          entityId: existing.id,
          affected: 0,
          data: existing,
          message: `Fiche de paie déjà existante (ID: ${existing.id})`,
        };
      }
    }

    const gross = Number(safeFields.gross_amount);
    const net = safeFields.net_amount !== undefined ? Number(safeFields.net_amount) : gross;

    const data = {
      ...safeFields,
      gross_amount: gross,
      net_amount: net,
      status: safeFields.status ?? PayslipStatus.DRAFT,
      payment_date:
        safeFields.status === PayslipStatus.PAID && !safeFields.payment_date
          ? new Date()
          : safeFields.payment_date,
    };

    const record = this.payslipRepo.create(data);
    const saved = await this.payslipRepo.save(record) as unknown as Payslip;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Fiche de paie créée (Brut: ${gross.toFixed(2)} €, Net: ${net.toFixed(2)} €)`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const payslip = await this.payslipRepo.findOne({ where: { id: entityId as any } });
    if (!payslip) throw new NotFoundException(`Fiche de paie ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(payslip, safeFields);

    // Si on passe à PAID sans payment_date → mettre aujourd'hui
    if (safeFields.status === PayslipStatus.PAID && !payslip.payment_date) {
      payslip.payment_date = new Date();
    }

    const saved = await this.payslipRepo.save(payslip);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Fiche de paie ${entityId} mise à jour`,
    };
  }
}
