// src/modules/referral/dossier-referral-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { DossierReferral, CommissionBasis, CommissionMode } from './entities/dossier-referral.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les apports de dossiers.
 * Logique métier :
 *   - dossier + referrer + commission_rate obligatoires
 *   - 0 < commission_rate ≤ 100
 *   - dossier_id UNIQUE → 1 seul apporteur par dossier
 *   - Dédup par dossier_id (retourne l'existant)
 *   - referral_date par défaut : today
 *   - commission_basis par défaut : COLLECTED_HT (encaissé HT)
 */
@Injectable()
export class DossierReferralWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(DossierReferral)
    private readonly referralRepo: Repository<DossierReferral>,
  ) {
    super('dossier_referral', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      dossier_id: { description: 'ID du dossier. Peut fournir "dossier".', required: true },
      referrer_id: { description: 'ID de l\'apporteur. Peut fournir "referrer" avec son nom.', required: true },
      commission_mode: { description: 'rate ou fixed_amount (defaut: rate)', example: 'rate' },
      commission_rate: { description: 'Taux de commission en % (requis si commission_mode=rate)', example: '10.00' },
      commission_amount: { description: 'Montant fixe de commission (requis si commission_mode=fixed_amount)', example: '25000.00' },
      commission_basis: {
        description: 'invoiced_ht, invoiced_ttc, collected_ht (défaut), collected_ttc',
        example: 'collected_ht',
      },
      referral_date: { description: 'Date d\'apport (par défaut: aujourd\'hui)', example: '2026-05-15' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.dossier_id) errors.push('Le dossier est requis (dossier_id ou dossier)');
      if (!fields.referrer_id) errors.push('L\'apporteur est requis (referrer_id ou referrer)');
      const mode = fields.commission_mode ?? CommissionMode.RATE;
      if (mode === CommissionMode.RATE && (fields.commission_rate === undefined || fields.commission_rate === null)) {
        errors.push('Le taux de commission est requis (commission_rate)');
      }
      if (mode === CommissionMode.FIXED_AMOUNT && (fields.commission_amount === undefined || fields.commission_amount === null)) {
        errors.push('Le montant fixe de commission est requis (commission_amount)');
      }
    }
    if (fields.commission_rate !== undefined) {
      const rate = Number(fields.commission_rate);
      if (rate <= 0) errors.push('Le taux de commission doit être strictement positif');
      if (rate > 100) errors.push('Le taux de commission ne peut pas excéder 100%');
    }
    if (fields.commission_amount !== undefined) {
      const amount = Number(fields.commission_amount);
      if (amount <= 0) errors.push('Le montant fixe de commission doit etre strictement positif');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    // Dédup par dossier_id (UNIQUE)
    if (safeFields.dossier_id) {
      const existing = await this.referralRepo.findOne({
        where: { dossier_id: safeFields.dossier_id },
      });
      if (existing) {
        this.logger.warn(
          `♻️  Apport déjà existant pour dossier ${existing.dossier_id} (apporteur: ${existing.referrer_id})`,
        );
        return {
          success: true,
          operation: 'INSERT',
          entityId: existing.id,
          affected: 0,
          data: existing,
          message: `Le dossier ${existing.dossier_id} a déjà un apporteur (ID: ${existing.id}). Utilisez UPDATE pour modifier.`,
        };
      }
    }

    const data = {
      ...safeFields,
      commission_mode: safeFields.commission_mode ?? CommissionMode.RATE,
      commission_rate: Number(safeFields.commission_rate ?? 0),
      commission_amount: safeFields.commission_amount != null ? Number(safeFields.commission_amount) : null,
      commission_basis: safeFields.commission_basis ?? CommissionBasis.COLLECTED_HT,
      referral_date: safeFields.referral_date ? new Date(safeFields.referral_date) : new Date(),
    };

    const record = this.referralRepo.create(data);
    const saved = await this.referralRepo.save(record) as unknown as DossierReferral;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Apport enregistré : dossier ${saved.dossier_id} → apporteur ${saved.referrer_id} (${Number(saved.commission_rate).toFixed(2)}%)`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const referral = await this.referralRepo.findOne({ where: { id: entityId as any } });
    if (!referral) throw new NotFoundException(`Apport ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    // dossier_id et referrer_id non modifiables (intégrité référentielle)
    delete safeFields['dossier_id'];
    delete safeFields['referrer_id'];

    Object.assign(referral, safeFields);
    const saved = await this.referralRepo.save(referral);

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Apport ${entityId} mis à jour`,
    };
  }
}
