export enum DossierLifecyclePhase {
  OPENING = 'OPENING',
  TREATMENT = 'TREATMENT',
  CLOSED = 'CLOSED',
}

export enum WorkflowEngine {
  LEGACY = 'LEGACY',
  ACTIONS_V2 = 'ACTIONS_V2',
}

export enum DossierActionStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ActionPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ActionLinkRole {
  INPUT = 'INPUT',
  OUTPUT = 'OUTPUT',
  EVIDENCE = 'EVIDENCE',
  DEPENDS_ON = 'DEPENDS_ON',
}

export enum ActionBillingDecision {
  NOT_DECIDED = 'NOT_DECIDED',
  BILLABLE = 'BILLABLE',
  NON_BILLABLE = 'NON_BILLABLE',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum RecommendationStatus {
  ACTIVE = 'ACTIVE',
  DEFERRED = 'DEFERRED',
  ACCEPTED = 'ACCEPTED',
  SUPERSEDED = 'SUPERSEDED',
  DISMISSED = 'DISMISSED',
}

export enum RecommendationTrigger {
  OPENING_VALIDATED = 'OPENING_VALIDATED',
  ACTION_COMPLETED = 'ACTION_COMPLETED',
  AUDIENCE_DUE = 'AUDIENCE_DUE',
  AUDIENCE_POSTPONED = 'AUDIENCE_POSTPONED',
  DOCUMENT_STATUS_CHANGED = 'DOCUMENT_STATUS_CHANGED',
  MISSING_DOCUMENT = 'MISSING_DOCUMENT',
  DEADLINE_REACHED = 'DEADLINE_REACHED',
  NO_OPEN_ACTION = 'NO_OPEN_ACTION',
  MANUAL = 'MANUAL',
}

export enum BillingMode {
  FIXED = 'FIXED',
  HOURLY = 'HOURLY',
  PERCENTAGE = 'PERCENTAGE',
  MIXED = 'MIXED',
}

export enum BillingTrigger {
  OPENING_VALIDATED = 'OPENING_VALIDATED',
  ACTION_COMPLETED = 'ACTION_COMPLETED',
  AUDIENCE_CREATED = 'AUDIENCE_CREATED',
  AUDIENCE_HELD = 'AUDIENCE_HELD',
  DILIGENCE_COMPLETED = 'DILIGENCE_COMPLETED',
  MANUAL = 'MANUAL',
}

export enum BillingCalculationMode {
  FIXED = 'FIXED',
  HOURLY = 'HOURLY',
  PERCENTAGE = 'PERCENTAGE',
  EXPENSE = 'EXPENSE',
}

export enum BillableItemStatus {
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  TO_INVOICE = 'TO_INVOICE',
  RESERVED = 'RESERVED',
  INVOICED = 'INVOICED',
  WAIVED = 'WAIVED',
  ADJUSTED = 'ADJUSTED',
}

export enum BillableSourceType {
  OPENING_FEE = 'OPENING_FEE',
  ACTION = 'ACTION',
  AUDIENCE = 'AUDIENCE',
  DILIGENCE = 'DILIGENCE',
  MANUAL = 'MANUAL',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum MigrationRunStatus {
  PREVIEWED = 'PREVIEWED',
  APPLIED = 'APPLIED',
  CONFIRMED = 'CONFIRMED',
  ROLLED_BACK = 'ROLLED_BACK',
  FAILED = 'FAILED',
}

export enum ClosureReviewStatus {
  CHECKED = 'CHECKED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
}
