// src/modules/customer/customer/customer-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { Customer, CustomerStatus, CustomerCreatedFrom } from './entities/customer.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les clients.
 * Logique métier :
 *   - (first_name + last_name) OU company_name obligatoires
 *   - customer_code généré par @BeforeInsert (déjà stripped via AUTO_GENERATED_FIELDS)
 *   - Dédup par email > téléphone > (first_name + last_name) > company_name (via BaseWriteHandler)
 *   - status par défaut : ACTIVE
 *   - created_from par défaut : AGENCY
 */
@Injectable()
export class CustomerWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(Customer)
    private readonly customerRepo: Repository<Customer>,
  ) {
    super('customer', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      first_name: { description: 'Prénom (obligatoire pour particulier)', example: 'Jean' },
      last_name: { description: 'Nom (obligatoire pour particulier)', example: 'Dupont' },
      company_name: { description: 'Raison sociale (obligatoire pour pro/entreprise)', example: 'SARL Dupont' },
      email: { description: 'Email du client (sert à la déduplication)', example: 'jean.dupont@mail.fr' },
      number_phone_1: { description: 'Téléphone principal', example: '+33 6 12 34 56 78' },
      type_customer_id: { description: 'ID du type. Peut fournir "type_customer" avec le code (PART/PRO/ENT/ASSO).' },
      branch_id: { description: 'ID de l\'agence. Peut fournir "branch".' },
      location_city_id: { description: 'ID de la ville. Peut fournir "location_city" avec le nom.' },
      status: { description: '1=Actif, 0=Inactif, -1=Supprimé', example: '1' },
      created_from: { description: '0=Agence, 1=En ligne', example: '0' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      const hasPerson = fields.first_name && fields.last_name;
      const hasCompany = fields.company_name;
      if (!hasPerson && !hasCompany) {
        errors.push('Fournir soit (first_name + last_name) pour un particulier, soit company_name pour une entreprise');
      }
    }
    // Validation format email basique
    if (fields.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(fields.email))) {
      errors.push('Format d\'email invalide');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    // Le strip AUTO_GENERATED_FIELDS + findDuplicateBy se font dans super.doInsert
    // donc on délègue après avoir injecté les défauts métier.
    const enriched = {
      ...fields,
      status: fields.status !== undefined ? Number(fields.status) : CustomerStatus.ACTIVE,
      created_from:
        fields.created_from !== undefined ? Number(fields.created_from) : CustomerCreatedFrom.AGENCY,
    };
    // Appel direct au flow standard avec les enrichissements
    return super.doInsert(enriched, userId);
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const customer = await this.customerRepo.findOne({ where: { id: entityId as any } });
    if (!customer) throw new NotFoundException(`Client ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    // Ne jamais écraser le customer_code
    delete safeFields['customer_code'];

    Object.assign(customer, safeFields);
    const saved = await this.customerRepo.save(customer);

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Client ${customer.customer_code} mis à jour`,
    };
  }
}
