import { Column, Entity, JoinColumn, ManyToOne, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { TenantEntity } from 'src/core/entities/tenant.entity';
import { SourceModule } from '../enums/comptabilite.enums';
import { JournalComptable } from './journal.entity';
import { ExerciceComptable } from './exercice.entity';
import { LigneEcriture } from './ligne-ecriture.entity';

@Entity('ecritures_comptables')
export class Ecriture extends TenantEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ unique: true, length: 30 })
  numero: string;

  @Column({ name: 'date_ecriture', type: 'date' })
  dateEcriture: Date;

  @Column({ length: 500 })
  libelle: string;

  @Column({ name: 'journal_id' })
  journal_id: number;

  @ManyToOne(() => JournalComptable, { eager: false })
  @JoinColumn({ name: 'journal_id' })
  journal: JournalComptable;

  @Column({ name: 'exercice_id' })
  exercice_id: number;

  @ManyToOne(() => ExerciceComptable, { eager: false })
  @JoinColumn({ name: 'exercice_id' })
  exercice: ExerciceComptable;

  @Column({ name: 'source_module', type: 'enum', enum: SourceModule, default: SourceModule.MANUEL })
  sourceModule: SourceModule;

  @Column({ name: 'source_id', nullable: true, length: 100 })
  sourceId: string;

  @Column({ name: 'is_auto_generated', default: false })
  isAutoGenerated: boolean;

  @Column({ name: 'is_locked', default: false })
  isLocked: boolean;

  @OneToMany(() => LigneEcriture, l => l.ecriture, { cascade: true, eager: true })
  lignes: LigneEcriture[];

  get totalDebit(): number {
    return this.lignes?.reduce((s, l) => s + Number(l.debit), 0) ?? 0;
  }

  get totalCredit(): number {
    return this.lignes?.reduce((s, l) => s + Number(l.credit), 0) ?? 0;
  }

  get estEquilibree(): boolean {
    return Math.abs(this.totalDebit - this.totalCredit) < 0.01;
  }
}
