import { Column, Entity, JoinColumn, ManyToOne, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { TenantEntity } from 'src/core/entities/tenant.entity';
import { SourceModule } from '../enums/comptabilite.enums';
import { JournalComptable } from './journal.entity';
import { ExerciceComptable } from './exercice.entity';
import { LigneEcriture } from './ligne-ecriture.entity';
import { BusinessTable, BusinessColumn } from 'src/core/decorators/business-metadata.decorator';

@Entity('ecritures_comptables')
@BusinessTable({
  label: 'Écritures comptables',
  description: 'Écritures du journal comptable (en partie double). Chaque écriture appartient à un journal et un exercice, et contient une ou plusieurs lignes (débit/crédit) qui doivent toujours être équilibrées (total débit = total crédit).',
  icon: '🧾',
  category: 'finance',
})
export class Ecriture extends TenantEntity {
  @PrimaryGeneratedColumn()
  @BusinessColumn({
    label: 'Identifiant',
    description: 'Identifiant unique de l\'écriture',
    importance: 'low',
    group: 'technique',
    ignored: true,
  })
  id: number;

  @Column({ unique: true, length: 30 })
  @BusinessColumn({
    label: 'Numéro',
    description: 'Numéro unique de l\'écriture (généré automatiquement, ex: VTE-2026-00001)',
    importance: 'critical',
    group: 'identification',
    ignored: true,
  })
  numero: string;

  @Column({ name: 'date_ecriture', type: 'date' })
  @BusinessColumn({
    label: 'Date de l\'écriture',
    description: 'Date à laquelle l\'écriture est comptabilisée',
    format: 'date',
    importance: 'critical',
    group: 'dates',
  })
  dateEcriture: Date;

  @Column({ length: 500 })
  @BusinessColumn({
    label: 'Libellé',
    description: 'Libellé général de l\'écriture',
    example: 'Facture client n°123, Achat de fournitures',
    importance: 'critical',
    group: 'contenu',
  })
  libelle: string;

  @Column({ name: 'journal_id' })
  journal_id: number;

  @ManyToOne(() => JournalComptable, { eager: false })
  @JoinColumn({ name: 'journal_id' })
  @BusinessColumn({
    label: 'Journal',
    description: 'Journal comptable dans lequel l\'écriture est enregistrée',
    importance: 'critical',
    group: 'relation',
  })
  journal: JournalComptable;

  @Column({ name: 'exercice_id' })
  exercice_id: number;

  @ManyToOne(() => ExerciceComptable, { eager: false })
  @JoinColumn({ name: 'exercice_id' })
  @BusinessColumn({
    label: 'Exercice',
    description: 'Exercice comptable concerné par l\'écriture',
    importance: 'high',
    group: 'relation',
  })
  exercice: ExerciceComptable;

  @Column({ name: 'source_module', type: 'enum', enum: SourceModule, default: SourceModule.MANUEL })
  @BusinessColumn({
    label: 'Module source',
    description: 'Module ayant généré l\'écriture (manuel si saisie directe)',
    importance: 'medium',
    group: 'classification',
  })
  sourceModule: SourceModule;

  @Column({ name: 'source_id', nullable: true, length: 100 })
  @BusinessColumn({
    label: 'ID source',
    description: 'Identifiant du document source (facture, paiement...) ayant généré l\'écriture',
    importance: 'low',
    group: 'classification',
    ignored: true,
  })
  sourceId: string;

  @Column({ name: 'is_auto_generated', default: false })
  @BusinessColumn({
    label: 'Générée automatiquement',
    description: 'True si l\'écriture a été générée automatiquement par un autre module',
    importance: 'low',
    group: 'état',
  })
  isAutoGenerated: boolean;

  @Column({ name: 'is_locked', default: false })
  @BusinessColumn({
    label: 'Verrouillée',
    description: 'True si l\'écriture est verrouillée et ne peut plus être modifiée',
    importance: 'medium',
    group: 'état',
  })
  isLocked: boolean;

  @OneToMany(() => LigneEcriture, l => l.ecriture, { cascade: true, eager: true })
  @BusinessColumn({
    label: 'Lignes',
    description: 'Lignes de débit/crédit composant l\'écriture',
    importance: 'critical',
    group: 'contenu',
  })
  lignes: LigneEcriture[];

  // ==================== GETTERS MÉTIER (calculés, pas des colonnes SQL) ====================

  @BusinessColumn({
    label: 'Total débit',
    description: 'Somme des débits des lignes de l\'écriture (champ calculé, ne PAS l\'utiliser dans une clause SQL — ce n\'est pas une colonne de la table)',
    importance: 'medium',
    group: 'résultat',
  })
  get totalDebit(): number {
    return this.lignes?.reduce((s, l) => s + Number(l.debit), 0) ?? 0;
  }

  @BusinessColumn({
    label: 'Total crédit',
    description: 'Somme des crédits des lignes de l\'écriture (champ calculé, ne PAS l\'utiliser dans une clause SQL — ce n\'est pas une colonne de la table)',
    importance: 'medium',
    group: 'résultat',
  })
  get totalCredit(): number {
    return this.lignes?.reduce((s, l) => s + Number(l.credit), 0) ?? 0;
  }

  @BusinessColumn({
    label: 'Équilibrée',
    description: 'True si total débit = total crédit (champ calculé, ne PAS l\'utiliser dans une clause SQL — ce n\'est pas une colonne de la table)',
    importance: 'medium',
    group: 'résultat',
  })
  get estEquilibree(): boolean {
    return Math.abs(this.totalDebit - this.totalCredit) < 0.01;
  }
}
