// src/modules/comptabilite/write/compte-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { CompteComptable } from '../entities/compte.entity';
import { ClasseCompte, TypeCompte } from '../enums/comptabilite.enums';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les comptes comptables (plan comptable SYSCOHADA).
 * Logique métier :
 *   - numero + libelle obligatoires à la création
 *   - classe déduite automatiquement du 1er chiffre du numéro si absente
 *   - dédup par "numero" (un compte ne peut exister 2x pour un même tenant)
 *   - actif par défaut : true
 */
@Injectable()
export class CompteWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(CompteComptable)
    private readonly compteRepo: Repository<CompteComptable>,
  ) {
    super('comptes_comptables', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      numero: { description: 'Numéro de compte SYSCOHADA (obligatoire)', example: '411000', required: true },
      libelle: { description: 'Libellé du compte (obligatoire)', example: 'Clients', required: true },
      typeCompte: { description: 'ACTIF, PASSIF, CHARGE ou PRODUIT' },
      classe: { description: 'Classe SYSCOHADA (1 à 8). Déduite du numéro si absente.' },
      actif: { description: 'BD: 1=Actif (par défaut), 0=Inactif.' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.numero) errors.push('Le numéro de compte est requis');
      if (!fields.libelle) errors.push('Le libellé du compte est requis');
    }
    if (fields.numero && !/^\d{1,10}$/.test(String(fields.numero))) {
      errors.push('Le numéro de compte doit être numérique (ex: 411000)');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    const existing = await this.compteRepo.findOne({ where: { numero: safeFields.numero } });
    if (existing) {
      return {
        success: true,
        operation: 'INSERT',
        entityId: existing.id,
        affected: 0,
        data: existing,
        message: `Compte ${existing.numero} déjà existant retourné (ID: ${existing.id}) — pas de doublon créé`,
      };
    }

    const classe = safeFields.classe ?? this.deduceClasse(safeFields.numero);
    const typeCompte = safeFields.typeCompte ?? this.deduceType(classe);

    const data = {
      ...safeFields,
      classe,
      typeCompte,
      actif: safeFields.actif !== undefined ? Boolean(Number(safeFields.actif)) : true,
    };

    const record = this.compteRepo.create(data);
    const saved = await this.compteRepo.save(record) as unknown as CompteComptable;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Compte "${saved.numero} — ${saved.libelle}" créé`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const compte = await this.compteRepo.findOne({ where: { id: entityId as any } });
    if (!compte) throw new NotFoundException(`Compte ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(compte, safeFields);
    const saved = await this.compteRepo.save(compte);

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Compte "${saved.numero}" mis à jour`,
    };
  }

  private deduceClasse(numero: string | undefined): ClasseCompte {
    const first = Number(String(numero ?? '6')[0]);
    return ([1, 2, 3, 4, 5, 6, 7, 8].includes(first) ? first : 6) as ClasseCompte;
  }

  private deduceType(classe: ClasseCompte): TypeCompte {
    switch (classe) {
      case ClasseCompte.CLASSE_1:
      case ClasseCompte.CLASSE_4:
        return TypeCompte.PASSIF;
      case ClasseCompte.CLASSE_2:
      case ClasseCompte.CLASSE_3:
      case ClasseCompte.CLASSE_5:
        return TypeCompte.ACTIF;
      case ClasseCompte.CLASSE_7:
        return TypeCompte.PRODUIT;
      default:
        return TypeCompte.CHARGE;
    }
  }
}
