// src/modules/comptabilite/write/exercice-write.handler.ts
import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { ExerciceComptable } from '../entities/exercice.entity';
import { StatutExercice } from '../enums/comptabilite.enums';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les exercices comptables.
 * Logique métier :
 *   - annee obligatoire à la création ; dateDebut/dateFin déduites si absentes
 *   - dédup par "annee" (un seul exercice par année et par tenant)
 *   - statut par défaut : OUVERT
 *   - passage à CLOTURE → renseigne dateCloture automatiquement
 */
@Injectable()
export class ExerciceWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(ExerciceComptable)
    private readonly exerciceRepo: Repository<ExerciceComptable>,
  ) {
    super('exercices_comptables', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      annee: { description: 'Année de l\'exercice (obligatoire)', example: '2026', required: true },
      dateDebut: { description: 'Date de début (par défaut 1er janvier de l\'année)', example: '2026-01-01' },
      dateFin: { description: 'Date de fin (par défaut 31 décembre de l\'année)', example: '2026-12-31' },
      statut: { description: "BD: 'OUVERT' ou 'CLOTURE'." },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT' && !fields.annee) {
      errors.push('L\'année de l\'exercice est requise');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    const annee = Number(safeFields.annee);

    const existing = await this.exerciceRepo.findOne({ where: { annee } });
    if (existing) {
      return {
        success: true,
        operation: 'INSERT',
        entityId: existing.id,
        affected: 0,
        data: existing,
        message: `Exercice ${existing.annee} déjà existant retourné (ID: ${existing.id}) — pas de doublon créé`,
      };
    }

    const data = {
      ...safeFields,
      annee,
      dateDebut: safeFields.dateDebut ? new Date(safeFields.dateDebut) : new Date(`${annee}-01-01`),
      dateFin: safeFields.dateFin ? new Date(safeFields.dateFin) : new Date(`${annee}-12-31`),
      statut: safeFields.statut ?? StatutExercice.OUVERT,
    };

    const record = this.exerciceRepo.create(data);
    const saved = await this.exerciceRepo.save(record) as unknown as ExerciceComptable;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Exercice ${saved.annee} créé`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const exercice = await this.exerciceRepo.findOne({ where: { id: entityId as any } });
    if (!exercice) throw new NotFoundException(`Exercice ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    if (safeFields.statut === StatutExercice.CLOTURE && exercice.statut !== StatutExercice.CLOTURE) {
      safeFields.dateCloture = safeFields.dateCloture ? new Date(safeFields.dateCloture) : new Date();
    }
    Object.assign(exercice, safeFields);

    let saved: ExerciceComptable;
    try {
      saved = await this.exerciceRepo.save(exercice);
    } catch (error) {
      throw new BadRequestException(this.translateDbError(error));
    }

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Exercice ${saved.annee} mis à jour`,
    };
  }
}
