// src/modules/comptabilite/write/journal-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { JournalComptable } from '../entities/journal.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les journaux comptables.
 * Logique métier :
 *   - code + libelle + typeJournal obligatoires à la création
 *   - dédup par "code" (un journal ne peut exister 2x pour un même tenant)
 *   - actif par défaut : true
 */
@Injectable()
export class JournalWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(JournalComptable)
    private readonly journalRepo: Repository<JournalComptable>,
  ) {
    super('journaux_comptables', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      code: { description: 'Code court du journal (obligatoire)', example: 'VTE', required: true },
      libelle: { description: 'Libellé du journal (obligatoire)', example: 'Journal des ventes', required: true },
      typeJournal: { description: 'VENTES, ACHATS, CAISSE, BANQUE ou OD (obligatoire)', required: true },
      actif: { description: '1=Actif (par défaut), 0=Inactif' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.code) errors.push('Le code du journal est requis');
      if (!fields.libelle) errors.push('Le libellé du journal est requis');
      if (!fields.typeJournal) errors.push('Le type de journal est requis (VENTES, ACHATS, CAISSE, BANQUE, OD)');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    const existing = await this.journalRepo.findOne({ where: { code: safeFields.code } });
    if (existing) {
      return {
        success: true,
        operation: 'INSERT',
        entityId: existing.id,
        affected: 0,
        data: existing,
        message: `Journal ${existing.code} déjà existant retourné (ID: ${existing.id}) — pas de doublon créé`,
      };
    }

    const data = {
      ...safeFields,
      actif: safeFields.actif !== undefined ? Boolean(Number(safeFields.actif)) : true,
    };

    const record = this.journalRepo.create(data);
    const saved = await this.journalRepo.save(record) as unknown as JournalComptable;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Journal "${saved.code} — ${saved.libelle}" créé`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const journal = await this.journalRepo.findOne({ where: { id: entityId as any } });
    if (!journal) throw new NotFoundException(`Journal ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(journal, safeFields);
    const saved = await this.journalRepo.save(journal);

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Journal "${saved.code}" mis à jour`,
    };
  }
}
