export enum MODE_REIMBURSEMENT_PERIOD {
  DAYLY = 'DAYLY',
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY', // 2-week
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY', // 3 or 4-month
  YEARLY = 'YEARLY',
}

export enum CREDIT_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CREDIT_STATE {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  INCOMPLETE = 'INCOMPLETE',
  IN_PROCESSING = 'IN_PROCESSING',
}

export enum TYPE_CREDIT_STATE {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  DISABLE = 'DISABLE',
}
