export enum MODE_REIMBURSEMENT_PERIOD {
  DAYLY = 1,
  WEEKLY = 7,
  BIWEEKLY = 14, // 2-week
  MONTHLY = 30,
  QUARTERLY_3 = 90, // 3 or 4-month
  QUARTERLY_4 = 120, // 3 or 4-month
  YEARLY = 365,
}

export enum CREDIT_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum CREDIT_STATE {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  INCOMPLETE = 'INCOMPLETE',
  IN_PROCESSING = 'IN_PROCESSING',
  END_PROCESSING = 'END_PROCESSING',
}

export enum TYPE_CREDIT_STATE {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  DISABLE = 'DISABLE',
}

export enum TYPE_STATUS {
  ACTIVE = 1,
  PENDING = 0,
  DISABLE = -1,
}

export const CREDIT_CODE = 'CD001';
