import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Ecriture } from '../entities/ecriture.entity';
import { ExerciceComptable } from '../entities/exercice.entity';
import { JournalComptable } from '../entities/journal.entity';
import { CompteComptable } from '../entities/compte.entity';
import { SourceModule, StatutExercice, TypeJournal } from '../enums/comptabilite.enums';
import { CreateEcritureDto } from '../dto/create-ecriture.dto';
import { InitialisationComptableService } from './initialisation.service';

@Injectable()
export class EcrituresService {
  constructor(
    @InjectRepository(Ecriture)
    private readonly ecritureRepo: Repository<Ecriture>,
    @InjectRepository(ExerciceComptable)
    private readonly exerciceRepo: Repository<ExerciceComptable>,
    @InjectRepository(JournalComptable)
    private readonly journalRepo: Repository<JournalComptable>,
    @InjectRepository(CompteComptable)
    private readonly compteRepo: Repository<CompteComptable>,
    private readonly initialisation: InitialisationComptableService,
  ) {}

  async creer(dto: CreateEcritureDto, isAuto = false): Promise<Ecriture> {
    // Résolution de l'exercice par ANNÉE de l'écriture.
    // Permet de comptabiliser des documents historiques (backfill) dans le bon
    // exercice fiscal. L'exercice est auto-créé s'il n'existe pas encore.
    const annee = new Date(dto.dateEcriture).getFullYear();
    let exercice = await this.exerciceRepo.findOne({ where: { annee } });
    if (!exercice) {
      exercice = await this.exerciceRepo.save(this.exerciceRepo.create({
        annee,
        dateDebut: new Date(`${annee}-01-01`),
        dateFin:   new Date(`${annee}-12-31`),
        statut:    StatutExercice.OUVERT,
      }));
    }
    // Une écriture manuelle ne peut pas être passée dans un exercice clôturé.
    // Les écritures système (événements / synchronisation) restent autorisées.
    if (exercice.statut === StatutExercice.CLOTURE && !isAuto) {
      throw new BadRequestException(`L'exercice ${annee} est clôturé`);
    }

    // Auto-réparation multi-tenant : si le plan comptable du tenant courant
    // n'a pas encore été créé (journal absent), on l'initialise puis on réessaie.
    // Couvre le cas d'un événement live reçu avant toute synchronisation.
    let journal = await this.journalRepo.findOne({ where: { typeJournal: dto.codeJournal } });
    if (!journal) {
      await this.initialisation.initialiser();
      journal = await this.journalRepo.findOne({ where: { typeJournal: dto.codeJournal } });
    }
    if (!journal) throw new BadRequestException(`Journal ${dto.codeJournal} introuvable`);

    const lignes = await Promise.all(
      dto.lignes.map(async l => {
        const compte = await this.compteRepo.findOne({ where: { numero: l.numeroCompte } });
        if (!compte) throw new BadRequestException(`Compte ${l.numeroCompte} introuvable`);
        return { compte_id: compte.id, debit: l.debit, credit: l.credit, libelle: l.libelle ?? dto.libelle };
      }),
    );

    const totalDebit  = lignes.reduce((s, l) => s + Number(l.debit), 0);
    const totalCredit = lignes.reduce((s, l) => s + Number(l.credit), 0);
    if (Math.abs(totalDebit - totalCredit) > 0.01) {
      throw new BadRequestException(
        `Écriture déséquilibrée : débit=${totalDebit} ≠ crédit=${totalCredit}`,
      );
    }

    const numero = await this.genererNumero(journal.code);

    const ecriture = this.ecritureRepo.create({
      numero,
      dateEcriture:    new Date(dto.dateEcriture),
      libelle:         dto.libelle,
      journal_id:      journal.id,
      exercice_id:     exercice.id,
      sourceModule:    dto.sourceModule ?? SourceModule.MANUEL,
      sourceId:        dto.sourceId,
      isAutoGenerated: isAuto,
      lignes,
    });

    return this.ecritureRepo.save(ecriture);
  }

  findAll(filters: Record<string, any> = {}): Promise<Ecriture[]> {
    return this.ecritureRepo.find({
      where: filters,
      relations: ['journal', 'exercice', 'lignes', 'lignes.compte'],
      order: { dateEcriture: 'DESC', id: 'DESC' },
    });
  }

  async findOne(id: number): Promise<Ecriture> {
    const e = await this.ecritureRepo.findOne({
      where: { id },
      relations: ['journal', 'exercice', 'lignes', 'lignes.compte'],
    });
    if (!e) throw new NotFoundException(`Écriture ${id} introuvable`);
    return e;
  }

  findBySource(sourceModule: SourceModule, sourceId: string): Promise<Ecriture[]> {
    return this.ecritureRepo.find({
      where: { sourceModule, sourceId },
      relations: ['journal', 'lignes', 'lignes.compte'],
    });
  }

  /**
   * Teste si un document source a déjà été comptabilisé dans un journal donné.
   * Sert de garde d'idempotence pour les écritures automatiques (événements +
   * synchronisation initiale) afin de ne jamais créer de doublon.
   */
  async existeParSource(sourceModule: SourceModule, sourceId: string, codeJournal?: TypeJournal): Promise<boolean> {
    const qb = this.ecritureRepo
      .createQueryBuilder('e')
      .where('e.source_module = :sm', { sm: sourceModule })
      .andWhere('e.source_id = :sid', { sid: sourceId });
    if (codeJournal) {
      qb.innerJoin('e.journal', 'j').andWhere('j.typeJournal = :tj', { tj: codeJournal });
    }
    const count = await qb.getCount();
    return count > 0;
  }

  async search(params: {
    journalId?: number;
    exerciceId?: number;
    sourceModule?: SourceModule;
    dateDebut?: string;
    dateFin?: string;
    page?: number;
    limit?: number;
  }): Promise<{ data: Ecriture[]; total: number }> {
    const qb = this.ecritureRepo
      .createQueryBuilder('e')
      .leftJoinAndSelect('e.journal', 'journal')
      .leftJoinAndSelect('e.exercice', 'exercice')
      .leftJoinAndSelect('e.lignes', 'lignes')
      .leftJoinAndSelect('lignes.compte', 'compte')
      .orderBy('e.dateEcriture', 'DESC')
      .addOrderBy('e.id', 'DESC');

    if (params.journalId)    qb.andWhere('e.journal_id = :jid',   { jid: params.journalId });
    if (params.exerciceId)   qb.andWhere('e.exercice_id = :eid',  { eid: params.exerciceId });
    if (params.sourceModule) qb.andWhere('e.source_module = :sm', { sm: params.sourceModule });
    if (params.dateDebut)    qb.andWhere('e.date_ecriture >= :dd', { dd: params.dateDebut });
    if (params.dateFin)      qb.andWhere('e.date_ecriture <= :df', { df: params.dateFin });

    const limit = params.limit ?? 50;
    const page  = params.page  ?? 1;
    qb.skip((page - 1) * limit).take(limit);

    const [data, total] = await qb.getManyAndCount();
    return { data, total };
  }

  private async genererNumero(codeJournal: string): Promise<string> {
    const annee = new Date().getFullYear();
    const count = await this.ecritureRepo.count();
    return `${codeJournal}-${annee}-${String(count + 1).padStart(5, '0')}`;
  }
}
