// src/modules/diligence/diligence-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { Diligence, DiligenceStatus, DiligencePriority, DiligenceType } from './entities/diligence.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les diligences.
 * Logique métier :
 *   - dossier + title + start_date + deadline obligatoires
 *   - deadline > start_date
 *   - Status par défaut : DRAFT
 *   - Priorité par défaut : MEDIUM
 *   - Status COMPLETED → completion_date = today
 *   - actual_hours default 0
 */
@Injectable()
export class DiligenceWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(Diligence)
    private readonly diligenceRepo: Repository<Diligence>,
  ) {
    super('diligences', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      dossier_id: { description: 'ID du dossier. Peut fournir "dossier".', required: true },
      title: { description: 'Titre de la diligence', example: 'Due diligence acquisition société X', required: true },
      start_date: { description: 'Date de début (YYYY-MM-DD)', example: '2026-05-01', required: true },
      deadline: { description: 'Date butoir (YYYY-MM-DD)', example: '2026-06-30', required: true },
      type: { description: 'acquisition, investment, ipo, compliance, litigation, contract', example: 'acquisition' },
      status: { description: 'draft, in_progress, review, completed, cancelled', example: 'draft' },
      priority: { description: 'low, medium, high, critical', example: 'medium' },
      assigned_lawyer_id: { description: 'ID de l\'avocat. Peut fournir "assigned_lawyer".' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.dossier_id) errors.push('Le dossier est requis (dossier_id ou dossier)');
      if (!fields.title) errors.push('Le titre est requis');
      if (!fields.start_date) errors.push('La date de début est requise');
      if (!fields.deadline) errors.push('La date limite est requise');
    }
    if (fields.start_date && fields.deadline) {
      if (new Date(fields.deadline) < new Date(fields.start_date)) {
        errors.push('La date limite doit être postérieure à la date de début');
      }
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    const data = {
      ...safeFields,
      start_date: new Date(safeFields.start_date),
      deadline: new Date(safeFields.deadline),
      type: safeFields.type ?? DiligenceType.ACQUISITION,
      status: safeFields.status ?? DiligenceStatus.DRAFT,
      priority: safeFields.priority ?? DiligencePriority.MEDIUM,
      actual_hours: safeFields.actual_hours !== undefined ? Number(safeFields.actual_hours) : 0,
      confidential: safeFields.confidential ?? true,
    };

    const record = this.diligenceRepo.create(data);
    const saved = await this.diligenceRepo.save(record) as unknown as Diligence;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Diligence "${saved.title}" créée (échéance: ${new Date(saved.deadline).toLocaleDateString('fr-FR')})`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const diligence = await this.diligenceRepo.findOne({ where: { id: entityId as any } });
    if (!diligence) throw new NotFoundException(`Diligence ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(diligence, safeFields);

    // Transition auto vers COMPLETED → completion_date
    if (safeFields.status === DiligenceStatus.COMPLETED && !diligence.completion_date) {
      diligence.completion_date = new Date();
    }

    const saved = await this.diligenceRepo.save(diligence);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Diligence "${saved.title}" mise à jour`,
    };
  }
}
