// src/modules/supplier/expense-report-write.handler.ts
import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { ExpenseReport, ExpenseReportStatus } from './entities/expense-report.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import { WriteableFieldSchema, ValidationResult } from 'src/core/ai-database/interface/entity-write-handler.interface';

/**
 * Handler custom pour les notes de frais.
 * Logique métier :
 *   - employee + title obligatoires
 *   - submission_date par défaut : aujourd'hui
 *   - Status par défaut : DRAFT
 *   - Transitions automatiques :
 *     · status=REIMBURSED sans reimbursement_date → today
 *   - total_amount est recalculé par ExpenseLineWriteHandler à chaque ligne
 */
@Injectable()
export class ExpenseReportWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(ExpenseReport)
    private readonly reportRepo: Repository<ExpenseReport>,
  ) {
    super('expense_report', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      employee_id: {
        description: 'ID du collaborateur. Peut fournir "employee" avec son nom.',
        example: '5',
        required: true,
      },
      title: {
        description: 'Objet de la note de frais',
        example: 'Déplacement Tribunal Lyon - Dossier #123',
        required: true,
      },
      status: { description: "BD: 'draft', 'submitted', 'approved', 'rejected', 'reimbursed'.", example: 'draft' },
      submission_date: { description: 'Date de soumission (par défaut: aujourd\'hui)', example: '2026-05-10' },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.employee_id) errors.push('Le collaborateur est requis (employee_id ou employee)');
      if (!fields.title) errors.push('L\'objet de la note de frais est requis (title)');
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(fields: Record<string, any>, userId: string): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));

    const data = {
      ...safeFields,
      submission_date: safeFields.submission_date ? new Date(safeFields.submission_date) : new Date(),
      status: safeFields.status ?? ExpenseReportStatus.DRAFT,
      total_amount: safeFields.total_amount !== undefined ? Number(safeFields.total_amount) : 0,
    };

    const record = this.reportRepo.create(data);
    const saved = await this.reportRepo.save(record) as unknown as ExpenseReport;

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Note de frais "${saved.title}" créée`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const report = await this.reportRepo.findOne({ where: { id: entityId as any } });
    if (!report) throw new NotFoundException(`Note de frais ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(this.filterKnownColumns(fields));
    Object.assign(report, safeFields);

    // Transitions automatiques
    if (safeFields.status === ExpenseReportStatus.REIMBURSED && !report.reimbursement_date) {
      report.reimbursement_date = new Date();
    }

    const saved = await this.reportRepo.save(report);
    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Note de frais ${entityId} mise à jour`,
    };
  }
}
