// src/modules/supplier/expense-line-write.handler.ts
import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { ExpenseLine } from './entities/expense-line.entity';
import { ExpenseReport } from './entities/expense-report.entity';
import { BaseWriteHandler } from 'src/core/ai-database/write/base-write-handler';
import { SchemaMetadataService } from 'src/core/ai-database/schema-metadata.service';
import { EntityResolverService } from 'src/core/ai-database/write/entity-resolver.service';
import { WriteResult } from 'src/core/ai-database/write/write-handler.registry';
import {
  WriteableFieldSchema,
  ValidationResult,
} from 'src/core/ai-database/interface/entity-write-handler.interface';
import { CaseBillingService } from '../case-workflow/services/case-billing.service';

/**
 * Handler custom pour les lignes de note de frais.
 * Logique métier :
 *   - expense_report + description + category + amount_ht obligatoires
 *   - Calcul automatique amount_ttc depuis amount_ht + tax_rate
 *   - expense_date par défaut : today
 *   - Après INSERT/UPDATE : recalcule total_amount de la note de frais parente
 */
@Injectable()
export class ExpenseLineWriteHandler extends BaseWriteHandler {
  constructor(
    dataSource: DataSource,
    schemaMetadata: SchemaMetadataService,
    entityResolver: EntityResolverService,
    @InjectRepository(ExpenseLine)
    private readonly lineRepo: Repository<ExpenseLine>,
    @InjectRepository(ExpenseReport)
    private readonly reportRepo: Repository<ExpenseReport>,
    private readonly caseBillingService: CaseBillingService,
  ) {
    super('expense_line', dataSource, schemaMetadata, entityResolver);
  }

  async getWriteableFieldsSchema(): Promise<WriteableFieldSchema[]> {
    const fields = await super.getWriteableFieldsSchema();
    const enrichments: Record<string, Partial<WriteableFieldSchema>> = {
      expense_report_id: {
        description:
          'ID de la note de frais parente. Peut fournir "expense_report".',
        example: '8',
        required: true,
      },
      description: {
        description: 'Détail de la dépense',
        example: 'Train Paris-Lyon A/R',
        required: true,
      },
      category: {
        description:
          'transport, accommodation, meal, bailiff, court_fees, office_supplies, other',
        example: 'transport',
        required: true,
      },
      amount_ht: {
        description: 'Montant HT (> 0)',
        example: '120.00',
        required: true,
      },
      tax_rate: { description: 'Taux TVA (%)', example: '20.00' },
      is_rebillable: {
        description: '1=refacturable au client, 0=non',
        example: '0',
      },
      rebilling_type: {
        description: "Nature client : 'EXPENSE' (frais) ou 'DISBURSEMENT' (d\u00e9bours)",
        example: 'EXPENSE',
      },
      dossier_id: {
        description: 'Dossier client obligatoire lorsque la ligne est refacturable',
        example: '15',
      },
      action_id: {
        description: 'Action du dossier ayant occasionn\u00e9 la d\u00e9pense',
        example: '0cfce36d-9aec-4ff2-83b8-f20d63866d22',
      },
      currency: { description: 'Devise de refacturation', example: 'XAF' },
      attachment_url: {
        description: 'Lien du justificatif, notamment requis pour un d\u00e9bours',
        example: 'https://storage.example/justificatif.pdf',
      },
    };
    for (const f of fields) {
      if (enrichments[f.name]) Object.assign(f, enrichments[f.name]);
    }
    return fields;
  }

  async validateFields(
    fields: Record<string, any>,
    operation: 'INSERT' | 'UPDATE',
  ): Promise<ValidationResult> {
    const errors: string[] = [];
    if (operation === 'INSERT') {
      if (!fields.expense_report_id)
        errors.push('La note de frais est requise (expense_report_id)');
      if (!fields.description) errors.push('La description est requise');
      if (!fields.category) errors.push('La catégorie est requise');
      if (fields.amount_ht === undefined || fields.amount_ht === null) {
        errors.push('Le montant HT est requis');
      } else if (Number(fields.amount_ht) <= 0) {
        errors.push('Le montant HT doit être strictement positif');
      }
    } else if (operation === 'UPDATE') {
      if (fields.amount_ht !== undefined && Number(fields.amount_ht) <= 0) {
        errors.push('Le montant HT doit être strictement positif');
      }
    }
    return { valid: errors.length === 0, errors, transformedFields: fields };
  }

  protected async doInsert(
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const safeFields = this.stripAutoGeneratedFields(
      this.filterKnownColumns(fields),
    );

    const amountHT = Number(safeFields.amount_ht);
    const taxRate = Number(safeFields.tax_rate ?? 0);
    const amountTTC =
      Math.round((amountHT + (amountHT * taxRate) / 100) * 100) / 100;

    const data = {
      ...safeFields,
      amount_ht: amountHT,
      tax_rate: taxRate,
      amount_ttc: amountTTC,
      expense_date: safeFields.expense_date
        ? new Date(safeFields.expense_date)
        : new Date(),
      is_rebillable:
        safeFields.is_rebillable !== undefined
          ? Boolean(safeFields.is_rebillable)
          : false,
    };

    if (data.is_rebillable && !safeFields.dossier_id) {
      throw new BadRequestException(
        'Un dossier est obligatoire pour refacturer une d\u00e9pense',
      );
    }

    const record = this.lineRepo.create(data);
    const saved = (await this.lineRepo.save(record)) as unknown as ExpenseLine;

    await this.recomputeReportTotal(saved.expense_report_id);
    await this.caseBillingService.syncExpenseLineById(
      saved.id,
      this.actorId(userId),
    );

    return {
      success: true,
      operation: 'INSERT',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Ligne de frais "${saved.description}" (${amountTTC.toFixed(2)} € TTC) ajoutée`,
    };
  }

  protected async doUpdate(
    entityId: string | number,
    fields: Record<string, any>,
    userId: string,
  ): Promise<WriteResult> {
    const line = await this.lineRepo.findOne({
      where: { id: entityId as any },
    });
    if (!line)
      throw new NotFoundException(`Ligne de frais ${entityId} introuvable`);

    const safeFields = this.stripAutoGeneratedFields(
      this.filterKnownColumns(fields),
    );
    Object.assign(line, safeFields);

    if (line.is_rebillable && !line.dossier_id) {
      throw new BadRequestException(
        'Un dossier est obligatoire pour refacturer une d\u00e9pense',
      );
    }

    if (
      safeFields.amount_ht !== undefined ||
      safeFields.tax_rate !== undefined
    ) {
      line.amount_ht = Number(line.amount_ht);
      line.tax_rate = Number(line.tax_rate);
      line.amount_ttc =
        Math.round(
          (line.amount_ht + (line.amount_ht * line.tax_rate) / 100) * 100,
        ) / 100;
    }

    const saved = await this.lineRepo.save(line);
    await this.recomputeReportTotal(saved.expense_report_id);
    await this.caseBillingService.syncExpenseLineById(
      saved.id,
      this.actorId(userId),
    );

    return {
      success: true,
      operation: 'UPDATE',
      entityId: saved.id,
      affected: 1,
      data: saved,
      message: `Ligne ${entityId} mise à jour, total de la note recalculé`,
    };
  }

  /** Recalcule total_amount de la note de frais à partir des lignes */
  private async recomputeReportTotal(reportId: number): Promise<void> {
    const lines = await this.lineRepo.find({
      where: { expense_report_id: reportId },
    });
    const total = lines.reduce((sum, l) => sum + Number(l.amount_ttc), 0);

    const report = await this.reportRepo.findOne({ where: { id: reportId } });
    if (report) {
      report.total_amount = Math.round(total * 100) / 100;
      await this.reportRepo.save(report);
      this.logger.log(
        `📊 Note de frais ${reportId} recalculée: total=${report.total_amount} €`,
      );
    }
  }

  private actorId(userId: string): number | null {
    const value = Number(userId);
    return Number.isInteger(value) && value > 0 ? value : null;
  }
}
